- WS2008R2/lisa/setupscripts/NET_SWITCH_NIC_MAC.ps1
- WS2008R2/lisa/xml/FTM_win2008r2.xml
- WS2012R2/lisa/xml/NET_Tests.xml
- Change network types automated on 2008R2
- Removed VLAN Trunking from 2008R2 xml as it is not automated yet
- Fix on 2012R2 NET Tests xml
> Change network type automated on 2008R2

- WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
- WS2012R2/lisa/xml/Perf_IPerf_IPv4_Panorama.xml
Now the tester doesn't have to enter the password manually
> Updated scp and ssh with identity file on iperf tests

- WS2012R2/lisa/setupscripts/KVP_ModifyNonExistKeyValue.ps1
- WS2012R2/lisa/setupscripts/NMI_SendAs_Unprivileged.ps1
Fixes: NMI_SendAs_Unprivileged didn't remove the user created if the test failed. KVP_ModifyNonExistKeyValue showed an error even with a succes test.
> Improved NMI & KVP tests

- WS2012R2/lisa/xml/NET_Tests.xml
As on some external NICs packets with a size larger than 1500 were not being sent, Jumbo Frames test is reverted to use Private NICs by default.
> Jumbo Frame test set to use Private

- WS2012R2/lisa/remote-scripts/ica/FCOPY_Check_Daemon.sh
- WS2012R2/lisa/remote-scripts/ica/FCOPY_non_ascii.sh
- WS2012R2/lisa/setupscripts/FCOPY_non_ascii.ps1
- WS2012R2/lisa/xml/FCOPY_Tests.xml
FCOPY_non_ascii will generate a 100MB file with non-ascii characters.
Then it will copy the file to the Linux VM. Finally, the script will
verify both MD5 checksums (on host and guest).
> Added FCOPY_non_ascii testcase

- WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh
- WS2012R2/lisa/xml/CoreTests.xml
NTP test is now waiting up to half an hour before giving a result
> Improved CORE_TymeSync_NTP

- WS2012R2/lisa/Infrastructure/Analyze-IperfResultsThroughputFromLinuxSar.ps1
- WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
- WS2012R2/lisa/setupscripts/NET_SendIPtoVM.ps1
- WS2012R2/lisa/xml/Perf_IPerf_IPv4_Panorama.xml
Created a Jenkins job which fully automates the IPERF panorama test case.
This job does the following:
- Copies the latest vhdx from a specified network path to all the test servers.
- Creates the VMs automatically with the given vhdx.
- Now the test NICs are added and configured automatically.
- Runs the Iperf tests.
- Gathers the logs and creates a log with the average bandwidth speeds in the results folder.
For this:
- changed the NET_SendIPtoVM.ps1 script to be able to retrieve IP addresses from any given remote server
- changes to perf_iperf_panorama_client.sh
- added Analyze-IperfResultsThroughputFromLinuxSar.ps1 to repository to parse sar results at the end of the tests.
> IPERF: Jenkins automation

- WS2012R2/lisa/Infrastructure/Analyze-IperfResultsThroughputFromLinuxSar.ps1
- WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
- fixed distribution specific option in sar log parser
- in sar log parser we get the test interface on which Iperf was run
- on SLES we check the existence of sysstat before running the tests
> IPERF: fix sar results parser

- WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
- WS2012R2/lisa/xml/DM_Tests.xml
1. Change timeout value on SaveRestore
2. Change startup memory on CleanShutdown from 75% to 80%
3. Increase number of tries for starting VM3 from 3 to 10 in
StartupHighCompete
> DM_Tests small fixes

- WS2012R2/lisa/setupscripts/FCOPY_basic.ps1
- WS2012R2/lisa/setupscripts/FCOPY_file_exists.ps1
- WS2012R2/lisa/setupscripts/FCOPY_large_file.ps1
- WS2012R2/lisa/setupscripts/FCOPY_non_ascii.ps1
- WS2012R2/lisa/setupscripts/FCOPY_overwrite.ps1
- WS2012R2/lisa/setupscripts/fcopy_repeated_delete.ps1
- WS2012R2/lisa/xml/FCOPY_Tests.xml
1. All FCOPY are now working on remote servers. This is done by
creating/copying the testfile on the server specified in lisa.
2. Small fix in XML file. NoReboot flag on FCOPY_non_ascii changed
because it prevented the next test to run properly
> Added remote run capability to FCOPY Tests

- WS2012R2/lisa/setupscripts/FCOPY_basic.ps1
- WS2012R2/lisa/setupscripts/FCOPY_file_exists.ps1
- WS2012R2/lisa/setupscripts/FCOPY_large_file.ps1
- WS2012R2/lisa/setupscripts/FCOPY_non_ascii.ps1
- WS2012R2/lisa/setupscripts/FCOPY_overwrite.ps1
- WS2012R2/lisa/setupscripts/fcopy_repeated_delete.ps1
On some WS the retrieved VHD path was missing "\" in the end.  Added a
check for that and a fix if necessary
> FCOPY path fix

- WS2012R2/lisa/remote-scripts/ica/provisionLinuxForLisa.sh
- WS2012R2/lisa/setupscripts/ProvisionSshKeys.ps1
1. There are different versions in Redhat  for example: RHEL6 and RHEL7. however, different commands are suitable for different versions.  so split them in file. 
2. the "Red*Hat*" can't match the result.
> Add the branch of RedHat version

- WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
- WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_server.sh
- WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
- WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/setupscripts/NET_SendIPtoVM.ps1
- WS2012R2/lisa/xml/NET_Performance.xml
NET: if static IP is ipv6, the interface file will be created accordingly to support it
PERF: Iperf Panorama can now be run with ipv4 or ipv6 address
Tested on RHEL 6, RHEL 7, Ubuntu 15.10 and SLES 12 sp1
> NET: Added IPV6 support

- WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
- WS2012R2/lisa/remote-scripts/ica/NET_PROMISC.sh
- WS2012R2/lisa/remote-scripts/ica/NET_STATIC_MAC.sh
- WS2012R2/lisa/remote-scripts/ica/NET_TEST_NETWORK.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/xml/NET_Tests_IPv6.xml
Tested on RHEL 5, 6, 7, SLES 11 sp4, 12 sp1, Ubuntu 15.10
ipv6 tests are not working on RHEL 6.
> NET: basic ipv6 tests added

- WS2012R2/lisa/setupscripts/ManualMem_Configure.ps1
- WS2012R2/lisa/setupscripts/ManualMem_HotAdd.ps1
- WS2012R2/lisa/setupscripts/ManualMem_HotAdd_Chunks.ps1
- WS2012R2/lisa/setupscripts/ManualMem_MultipleAddRemove.ps1
- WS2012R2/lisa/setupscripts/ManualMem_StressHotRemove.ps1
- WS2012R2/lisa/xml/ManualMem_HotAdd_Tests.xml
This suite tests the memory Hot Add capability while Dynamic Memory is
disabled. It has 8 testcases: 
- HotAdd (increase memory with a big value, e.g 2GB)
- HotRemove ( decrease memory with a big value, e.g. 2GB)
- SmallIncrease128 (increase memory with 128MB chunks - 4 repeats) 
- SmallDecrease128 (decrease memory with 128MB chunks - 4 repeats) 
- SmallIncrease100 (increase memory with 100MB chunks - 4 repeats) 
- SmallDecrease100 (decrease memory with 100MB chunks - 4 repeats)  
- MultipleAddRemove ( increase and decrease memory with big values, e.g. 1-2 GB )
- StressHotRemove ( decrease memory while stress test is running)
All tests include a stress test to verify if VM can run workloads after the memory changed.
> New test suite added: Manual Memory Hot Add

- WS2012R2/lisa/remote-scripts/ica/Performance_FIO.sh
Deleted "Number of disk attached" message and included "Kernel_version= $(uname -r)" message.
> Add kernel_version parameter in log.

- WS2012R2/lisa/xml/CoreTests.xml
The hv_utils.ko that used to connect with integration serviceisn't necessary in VM temporary booting process, however the hyperv_fb.ko should add into checking list, so that the it is used when VM is booted.
> fix the list of checking modules

- WS2012R2/lisa/setupscripts/ChangeCPU.ps1
- WS2012R2/lisa/xml/CoreTests.xml
1. xml need to add onError or else the following cases can't be run 
2. fix get the maxCPUs
3. convert sting get from xml to int otherwise here is error:
`if ($numCPUs -lt 1 -or $numCPUs -gt $maxCPUs)
166 {
167     "Error: Incorrect VCPU value: $numCPUs (max CPUs = $maxCPUs)"
168 }
`
if $maxCPUs=24 rather than vcpu is set 4 the result is error
> fix mirror of getting error num of CPU and covert string to int

- WS2012R2/lisa/remote-scripts/ica/pxe_install.sh
- WS2012R2/lisa/xml/PXE_gen2.xml
PXE_gen2.xml creates a generation 2 VM and verifies/installs a supported
linux distro on it.
Supported Linux distributions: RHEL, SLES, Ubuntu
Important: For this test suite to work, you need to have a PXE Server
already set up with tftp, dhcp and http servers
> Added Gen2 support for PXE Install Test Suite

- WS2012R2/lisa/remote-scripts/ica/provisionLinuxForLisa.sh
- WS2012R2/lisa/remote-scripts/ica/provisionUtilVMForLisa.sh
- WS2012R2/lisa/setupscripts/Add-VHDXHardDiskWithLocation.ps1
- WS2012R2/lisa/setupscripts/NET_ADD_Switch.ps1
- WS2012R2/lisa/xml/ProvisionUtilVM.xml
1. Some cases during testing process need to use some storage like ISCSI and NFS, Add a script of deploy vm Client to set up NFS and ISCSI server automatically meanwhile also add an Internal Switch for the related Network performance cases. 
2 Add default location support if it is not set . 
3. Fixed stop firewall issue for RHEL7
4. Some cases refer to Network need to set the 2rd VM(IP), For some cases need to deploy env , we can do it ahead in provisioning client VM
> Provision client vm

- WS2012R2/lisa/Infrastructure/PXE/autoinstGen1.xml
- WS2012R2/lisa/Infrastructure/PXE/autoinstGen2.xml
- WS2012R2/lisa/Infrastructure/PXE/ks.cfg
- WS2012R2/lisa/Infrastructure/PXE/routingScript.sh
- WS2012R2/lisa/Infrastructure/PXE/ubuntu.seed
- WS2012R2/lisa/Infrastructure/PXE/ubuntuGen2.seed
- WS2012R2/lisa/docs/PXEGuide.md
- WS2012R2/lisa/remote-scripts/ica/pxe_install.sh
- WS2012R2/lisa/setupscripts/pxe_install.ps1
- WS2012R2/lisa/xml/PXE_gen1.xml
- WS2012R2/lisa/xml/PXE_gen2.xml
1. Added documentation. This includes a guide on how to run the PXE Test Suite and also a guide on how to setup a PXE Server. It can be found in /docs folder.
2. Added CentOS support. The distros supported now are: CentOS, RHEL, SLES and Ubuntu
3. Added install configuration files for all distros. These can be found in /Infrastructure/PXE folder. Although PXE Test Suite can be run with these default files, they can also be changed for a specific use case (post script, more packages, etc)
> PXE Test Suite improvements

- WS2012R2/lisa/remote-scripts/ica/PC_Stop_VSS_Daemon.sh
- WS2012R2/lisa/setupscripts/Production_checkpoint.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_3Chain_VHD.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_ISO_NoNetwork.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_failback.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_iSCSI.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_partition.ps1
- WS2012R2/lisa/xml/Production_Checkpoint.xml
This test suite will check Production Checkpoint feature in WS2016. Test
list:
1. ProductionCheckpoint - basic test: Create a file on the VM; take
checkpoint; create second file; revert to the checkpoint & check for the
first file created
2. ProductionCheckpoint_Failback - VSS daemon is stopped inside VM and
then a Production checkpoint is taken. Test passes if a standard
checkpoint is taken instead
3. ProductionCheckpoint_ext3 - attach a vhd on IDE, format it in
ext3 & mount it.
4. ProductionCheckpoint_ext4 - attach a vhd on IDE, format it in
ext4 & mount it.
5. ProductionCheckpoint_btrfs - attach a vhd on IDE, format it in
btrfs & mount it.
6. ProductionCheckpoint_IDE_SCSI - attach 2 vhds on IDE and SCSI,
format them in ext4 & mount.
7. ProductionCheckpoint_SCSI_vhdx - attach a vhdx on …
> Added Production Checkpoint test suite

- WS2012R2/lisa/setupscripts/Kdump.ps1
- WS2012R2/lisa/xml/Kdump_Tests.xml
1. 'at' usage was removed, instead we will use stderr to avoid plink
freezing. This should make crash triggering more stable. Also,
Test-NetConnection was removed, instead, an existing function will be
used to verify the VM status.
2. Crash_DifferentVCPU testcase was added. This will start the VM with 4
vcpus and trigger a kdump on VCPU 2 of (0-3). Usually, by default kdump
is triggered on VCPU 0 or 1
> Kdump improvements

- WS2012R2/lisa/setupscripts/ManualMem_HotAdd_reboot.ps1
- WS2012R2/lisa/xml/ManualMem_HotAdd_Tests.xml
Verify that memory changes with non 128-MB aligned values. This test
will start a vm with 4000 MB and will hot add 1000 MB to it. After that,
will reboot the vm and hot add another 1000 MB. Test will pass if all
hot add operations work.
> New Manual Memory Hot Add test case

- WS2012R2/lisa/lisa.ps1
lisa.ps1 will now accept a new argument, CLImageStorDir, which is
represented in XML files by imageStoreDir tag. If CLImageStorDir parameter
is given to lisa:
- it will check if path exists
- it will check if XML file given has this tag in first place. If the
XML doesn't have this tag, lisa won't change anything
- if imageStoreDir tag is present in XML file, it will be overwritten
with the value given at runtime
> Added CLImageStorDir variable for lisa.ps1

- WS2012R2/lisa/stateEngine.ps1
Fix the nextstatus when pretest script run fail or else left cases in xml will be not ran.
> fix the nextstatus when pretest script run fail

- WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
Wrapping script function calls to allow sourcing without code execution. Tested on Centos, Sles and Ubuntu.
> Adding perf_utils.sh sourcing possibility without code execution

- WS2012R2/lisa/Infrastructure/lisa-parser/file_parser.py
- WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser.py
- WS2012R2/lisa/Infrastructure/lisa-parser/test_run.py
Tested manually on an NTTTCP generated zipped log results with the following command:
python lisa_parser.py <lisa_xml_testcase> <ica_log> -p <full_path_zipped_log> -c <db_config>
> Add log parser to upload results for NTTTCP and FIO performance test cases

- WS2012R2/lisa/setupscripts/DM_HighPriority.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd.ps1
- WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_Stress_ng.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_stressapptest.ps1
- WS2012R2/lisa/setupscripts/DM_MaxMemHonor.ps1
- WS2012R2/lisa/setupscripts/DM_PressureChangesDemand.ps1
- WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/DM_Tests.xml
- Switch to stress-ng as memory stress test app (HotAddStressapptest remains the only one using stressapptest as reference)
- Created an application checking function in TCUtils. This is now used to check if stress-ng/stressapptest is present.
- Changed the way memory is calculated and how pressure is applied.
- Adjusted a few memory setting in the XML.
Tested successfully on: Centos 6.8, RHEL 7.2 (gen 1 and gen 2), Ubuntu 16 and SLES 12 sp 2
> Dynamic Memory refactoring

- WS2012R2/lisa/setupscripts/FC_AddFibreChannelHba.ps1
- WS2012R2/lisa/xml/FC_Tests.xml
Now you can specify different port addresses for fibre channel tests
through parameters in an xml file - WWNN=portA,portB - WWPN=portA,portB
If the specific addresses are already in use by some other local VM
the test will fail.
> Add support for specific port addresses on FC tests

- WS2012R2/lisa/setupscripts/FC_AddFibreChannelHba.ps1
When checking if a FC port value is used by another VM
another step was added so that the test can continue if
the other VMs are in an off state
> Check state for VMs that are using same ports

- WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/sql_utils.py
- WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/virtual_machine.py
In some cases VMs don not have snasphots available
so we have to catch errors that appear when calling
revert_snapshot
> Catch RuntimeError when trying to restore snapshot

- WS2012R2/lisa/remote-scripts/ica/NET_MAX_NIC.sh
On some cases the partial comparison that was previously
present in the function did not work properly ('eth1' ~= 'eth11')
The comparison was removed in favour of a strict match between
interface names.
> Refactor CheckGateway method

- WS2012R2/lisa/lisa.ps1
- WS2012R2/lisa/stateEngine.ps1
A new debug file was added that covers more details
regarding the state of a VM for a failing test case
The feature is enabled during LISA runs by setting the
<collect> parameter as True
> Added debug file for test cases that fail

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
- WS2012R2/lisa/xml/Kdump_Tests.xml
add following kdump extra parameters to for RHEL 5.x, 6.0-6.2
-- kdump.conf
core_collector makedumpfile -c --message-level 1 -d 31
disk_timeout 100
blacklist hv_vmbus hv_storvsc hv_utils hv_netvsc hid-hyperv hyperv_fb hyperv-keyboard
extra_modules ata_piix sr_mod sd_mod
-- /etc/sysconfig/kdump
- append to KDUMP_COMMANDLINE_APPEND
"irqpoll maxcpus=1 reset_devices ide_core.prefer_ms_hyperv=1"
> add extra kdump parameters for rhel 5.x, 6.0, 6.1, 6.2

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Broadcast.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_MaxNIC.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_iPerfStress.sh
- WS2012R2/lisa/setupscripts/NET_UTILS.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_ChangeRSS.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_DisableVMQ.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_MaxVMs.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_Ping_DisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_enable.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_DisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_MultipleServers.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_Reboot.ps1
- WS2012R2/lisa/xml/SR-IOV.xml
- WS2012R2/lisa/xml/SR-IOV_LM.xml
Added the following new TCs:
- Broadcast packet test
- Multicast packet test
- Multiple Linux sending TCP traffic to same host
- Continuous Ping, disable SR-IOV, enable SR-IOV
- iPerf, disable SR-IOV, enable SR-IOV
- Change RSS settings during iPerf
- Tear down VMQ and fallback to synthetic NIC
- Limit test – 32 VMs, one SR-IOV device each
- Limit test – one VM with max NICs, max SR-IOV devices
- Reboot during iPerf then connect successfully
- iPerf Stress test
For more detailed info, please check the FTM Automation spreadsheet
Important note: Also changed all SR-IOV TC_Covered codes to accommodate
the new TCs
> SR-IOV - Added 11 new Test Cases

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_DisableVF.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_basic.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_fileCopy.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_VerifyVF_basic.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_compareRTT.sh
- WS2012R2/lisa/setupscripts/SR-IOV_SavePauseVM.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_ShutDown_Dependency.ps1
- WS2012R2/lisa/xml/SR-IOV.xml
Old TCs are now using functions from SR-IOV_Utils.sh. Duplicate code was
significantly reduced.
A cleanup script was also added for turning off the dependency VM or VMs
where is the case.
> SR-IOV - Improvements to old TCs

- WS2012R2/lisa/setupscripts/MultipleReboot.ps1
- WS2012R2/lisa/xml/StressTests.xml
There was an issue with this script because it formerly tried to reboot
the VM both using the "Restart-VM" cmdlet and the ctrl-alt-del keystroke
from the VM's keyboard. This led to the occasional situation where the VM
would get stuck in the GRUB menu, failing the test this way.
In order to fix this, I removed the "ctrl-alt-del" reboot from the main
loop (Why was the VM being restarted twice with just a "sleep 5" between those
reboots?) alongside the VM keyboard variable (which only needs to be
initialized once). I also left a "ctrl-alt-del" reboot outside of the
loop, in case we need to test if rebooting with that method works aswell.
Also the boot count parameter is defined in the stress tests xml now,
therefore the script has been renamed to "MultipleReboot.ps1"
Also added indentation …
> Update 50 Reboot test script

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
Made two changes in automation scripts.
One in utils.sh in order to prevent cases were RHEL 6.7 was interpreted as RHEL 7.* in is_rhel7 function.
The other in kdump_config.sh where the case of a VM configured with UEFI was not properly handled.
> Automation fix

- WS2012R2/lisa/setupscripts/DiffDiskGrowthTestCase.ps1
Updated the partition on which the grown command was executed. The
previous one did not exist.
> Fixed AddDiff_Disk_IDE and AddDiff_Disk_SCSI

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_UpgradeKernel.sh
- WS2012R2/lisa/setupscripts/SR-IOV_MeasureDisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_MoveVHD.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_SavePauseVM.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_UpgradeKernel.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_UpgradePF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_Reboot.ps1
- WS2012R2/lisa/xml/SR-IOV.xml
- WS2012R2/lisa/xml/SR-IOV_LM.xml
1. Added 4 TCs:
- Host PF driver update/downgrade, SR-IOV in guest should work without
any interrupts
- Guest kernel update, SR-IOV should work without any interrupts
- Switch network between SR-IOV and netvsc synthetic data path back and
forth, the switch should happen immediately
- Switch network between SR-IOV and netvsc synthetic data path back and
forth, the switch should happen immediately
- Move the VHD to another host, and build a new VM based on this VHD.
The SR-IOV should work.
2. Make A change to existing TC - iPerfReboot to check the ifconfig
bytes/packets stats (should zeroed out those counters)
3. Changed Save/Pause TC to check if RTT values are lower (consistent
with VF in use)
4. Changed SR-IOV TC numbers to accommodate the new TCs
> SR-IOV: 4 TCs added

- WS2012R2/lisa/utilFunctions.ps1
Added build check before major and minor version verification.
> Fix OS version dependency check by superseding the build number

- WS2012R2/lisa/xml/FCOPY_Tests.xml
- WS2012R2/lisa/xml/NMI_Tests.xml
- WS2012R2/lisa/xml/Production_Checkpoint.xml
- WS2012R2/lisa/xml/Runtime_Memory_Resize_Tests.xml
- WS2012R2/lisa/xml/SR-IOV.xml
- WS2012R2/lisa/xml/STOR_VHDX.xml
- WS2012R2/lisa/xml/STOR_VHDXResize.xml
- WS2012R2/lisa/xml/STOR_VSS_Backup_Tests.xml
We can tag feature's test areas to define the minimum host side build ID from which the feature is supported.
We use build ID's to make them SKU names independent.
> Added minimum Hyper-V host version for features

- WS2012R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
In some cases the interface does not receive
a new IP address immediately so a wait time was added
to solve this.
> Added IP check after test ends

- WS2012R2/lisa/remote-scripts/ica/NET_Copy_Different_MTU.sh
- WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh
New distros use VMBUS instead of vmbus for naming in /sys/devices. Now a
check is made for lowercase and uppercase
> NET Tests small improvements

- WS2012R2/lisa/setupscripts/SR-IOV_ChangeRSS.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_DisableVMQ.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_MeasureDisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_Ping_DisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_SavePauseVM.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_UpgradeKernel.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_UpgradePF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_DisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_Reboot.ps1
1. Get the test VMs ipv4 again during testing, to make sure that the
bash scripts are sent to the correct VM
2. Tweak the accepted variations in RTT or throughput for more
precise results
3. Removed RestartVF function. The VF should automatically restart,
so there is no need for a forced restart
> SR-IOV: Various fixes and tweaks in automation

- WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
- WS2012R2/lisa/xml/NET_Tests.xml
- WS2012R2/lisa/xml/SR-IOV.xml
Download link for Omping is now broken for Ubuntu. We will use the
omping archive in tools folder instead of the web download from now
> Fixed Omping issue for Ubuntu

- WS2012R2/lisa/setupscripts/CORE_reload_modules.ps1
In some cases the test was failing due to
a loss in connection between LISA and the test VM.
A change was made so that the bash test script is now
being run as a background service while the powershell
script, that runs on the server, checks for updates in the
state.txt file.
> Fixed lost connection issue

- WS2012R2/lisa/setupscripts/InjectIPconstants.ps1
- WS2012R2/lisa/setupscripts/NET_SendIPtoVM.ps1
- WS2012R2/lisa/setupscripts/NET_UTILS.ps1
- WS2012R2/lisa/setupscripts/StartVM.ps1
- WS2012R2/lisa/xml/NET_Tests.xml
This solves https://github.com/LIS/lis-test/issues/554 
1. Fixed getRandUnusedMAC function
2. No more static MACs are used in the XML file. All MAC addresses are
now random-generated
> NET_TESTS improvements

- WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
Change $sleepTime from 60 to 5, original sleep duration is too long, which makes case spend too much time, and change WaitforVMtoStartKVP as WaitforVMToStartSSH to make stable.
> reduce STOR_VHDXResize_GrowShrink not necessary sleep time

- WS2012R2/lisa/setupscripts/CORE_reload_modules.ps1
The StressRealoadModules automation failed
because the PS script exited before the
bash script finished running on VM. In order to fix
that the number of checks performed from the host,
on the VM state file, was increased from 100 to 200 (with a 10s
sleep time in between attempts).
> Increased attempts number

- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/stateEngine.ps1
- WS2012R2/lisa/utilFunctions.ps1
Support test result return skip status.
For shell, support "TestSkipped", for powershell, can return  "$Skipped, $Passed, $Aborted, $Failed" if source TCUtils.ps1 in the test script , or needs to return string "Skipped", "Passed, "Aborted", "Failed", also support $True, $False as return value.
> Add test case skipped status by migrating xiaofeng commit

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
On RHEL 6.2 or lower the extra kdump configurations were not being made due to improper version comparison. A change was made so that the full version is evaluated now.
> Fixed version comparison for extra settings config

- WS2012R2/lisa/remote-scripts/ica/CORE_LISdaemons_selinux.sh
Add "ausearch -m user_avc" besides "ausearch -m avc" when search audit log, refer to bug https://bugzilla.redhat.com/show_bug.cgi?id=1377276, even the test scenario is different and this bug status is new.
> Update LISdaemons_selinux to add ausearch -m user_avc

- WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_Configure.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd_Chunks.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd_reboot.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_MultipleAddRemove.ps1
- WS2012R2/lisa/setupscripts/Runtime_Mem_StressHotRemove.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
Moved ConvertToMemSize from different files in TCUtils to reduce redundancy.
> Moved ConvertToMemSize method to TCUtils

- WS2012R2/lisa/remote-scripts/ica/modules_check.sh
- WS2012R2/lisa/xml/CoreTests.xml
Test was failing due to an automation issue. When updating state was
changed from function to utils.sh, the function names were not replaced.
> Fixed initrd_modules_check TC

- WS2012R2/lisa/remote-scripts/ica/LIS_daemons.sh
Fixed an issue where daemons were not successfully stopped on CentOS 6.x
> Fixed LIS_daemons.sh daemon stopping procedure

- WS2012R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
hv_vmbus and hv_netvsc can be kernel built-in , no longer failing test
if these modules are not showing up in the list of loaded modules.
> Code redesign for stress reload modules test

- WS2012R2/lisa/remote-scripts/ica/Hyperv_Daemons_Files_Status.sh
After rhel7.3 release with hyperv-daemons version hyperv-daemons-0-0.29.20160216git.el7.x86_64, there are no related hypervkvpd, hypervfcopyd, hypervvssd service files under /etc/systemd/system/multi-user.target.wants, also due to no impact on older versions,  directly remove service check under multi-user.target.wants folder.
Thank you.
> Update Hyperv_Daemons_File_Status by removing multi-user.target.wants

- WS2012R2/lisa/remote-scripts/ica/FCOPY_Check_Daemon.sh
Reverts LIS/lis-test#642
This change is breaking the compatibility with RHEL 6.x.
Please properly test the changes on rhel 6.x and 7x, plus Fedora, if that is needed support.
> Revert "Update FCOPY_Check_Daemon to support Fedora"

- WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1
Given that vxlan is not supported on 32 bit OS, test script will now
check for 32 bit guest. If the test VM is 32bit, TC will enter Test
Skipped state.
> Added additional check on NET_Hang_Vxlan.ps1

- WS2012R2/lisa/remote-scripts/ica/nmi_verify_interrupt.sh
- WS2012R2/lisa/setupscripts/NMI_Verify_Interrupt.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/NMI_Tests.xml
Refer to http://driverdev.linuxdriverproject.org/pipermail/driverdev-devel/2016-November/097202.html:
Prior to WS2016 the NMI is injected to all CPUs of the guest and WS2016 injects it to CPU0 only.
Update:
1. Remove NMI_Send_Interrupt, combine it to NMI_Verify_Interrupt
2. When host version is older than WS2012R2, return skipped
3. When host version is WS2012R2, check the NMI is injected to all CPUs of the guest
4. When host version is WS2016, check the NMI is only injected to CPU0
> Combine NMI_Send_Interrupt to NMI_Verify_Interrupt and update NMI_Verify_Interrupt

- WS2012R2/lisa/setupscripts/STOR_VHDXResize_Basic.ps1
- WS2012R2/lisa/setupscripts/STOR_VHDXResize_DiskOver2TB.ps1
- WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowFS.ps1
- WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
Add skipped if host version is lower than 2012R2, even already have <dependency> in the case STOR_VHDXResize.xml file, currently it cannot return skip, locally(downstream) we run same xml file for all the cases, so open this pull request.
Thank you
> Add Stor VHDXResize skipped if host version lower than 9600

- WS2012R2/lisa/setupscripts/TCUtils.ps1
GetVMGeneration method was not returning a value on WS2012 and some
Storage tests used to fail because of that.
> Fix GetVMGeneration method

- WS2012R2/lisa/xml/NET_Tests.xml
Updated CopyFileSCP to use dynamic VHDX instead of fixed VHDX
to reduce pretesting time
> Updated CopyFileSCP to use dynamic VHDX

- WS2012R2/lisa/setupscripts/INST_LIS_ShutdownServiceDisableEnable.ps1
Duplicate function CheckVMState was present in script and TCUtils,
causing different exit code and for the automation to fail
> Fix functions conflict in Shutdown service test

- WS2012R2/lisa/setupscripts/INST_LIS_TestVMShutdown.ps1
- WS2012R2/lisa/setupscripts/VMBus_PanicNotifier.ps1
VMBus panic notifier is supported only on WS2012R2 and newer, exiting
automation with Skip state otherwise
> Skip vmbus panic notifier on older platforms

- WS2012R2/lisa/setupscripts/CORE_RebootDiffMemory.ps1
In some cases the 20 seconds timeout was too low, and TC returned false
errors
> CORE: Increase timeout in 'Reboot Different Memory Settings' TC

- WS2012R2/lisa/remote-scripts/ica/Hyperv_Daemons_Files_Status.sh
- WS2012R2/lisa/setupscripts/Hyperv_Daemons_Basic.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
Hyper-v 2012 host does not support backup and fcopy feature, in the vm side, even related file available in the related file, here also ignore check, only verify hypervkvpd status.
> Skip hypervvssd and hypervfcopyd check for hyperv 2012 host

- WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
Increase the number of packets sent from 99 to 299 in order to get
better accuracy
Remove the check for duplicate packets, these are unlikely to show up
in a basic check
> NET Multicast test case update

- WS2012R2/lisa/remote-scripts/ica/FC_WWN.sh
RHEL 5.x and 6.x with kernel 2.6 do not have the FC WWN support.
Changing validation to kernel rather than by distro version.
> FC WWN change skip condition

- WS2012R2/lisa/remote-scripts/ica/check_clocksource.sh
The script was looking only into one value in clocksource. All values
that contain hyperv_clocksource are now ok
> Improvement to check_clocksource.sh

- WS2012R2/lisa/xml/NET_Tests.xml
When using legacy network adapters we must default to 1 vCPU on the VMs
> Fix for legacy NIC tests

- WS2012R2/lisa/setupscripts/STOR_VHDXResize_BasicLM.ps1
- WS2012R2/lisa/xml/STOR_VHDXResize.xml
Check if the VM runs on a cluster, if not skip the test case.
Previous behavior was to still run the test
> Add Skip condition for VHDx Resize on LM test

- WS2012R2/lisa/setupscripts/Production_checkpoint.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_3Chain_VHD.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_ISO_NoNetwork.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_failback.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_iSCSI.ps1
- WS2012R2/lisa/setupscripts/Production_checkpoint_partition.ps1
Exit with state Skipped if Production checkpoint automation is ran on
anything older than WS2016
> skip state for Production Checkpoint if NA

- WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh
In case ntpq command outputs an error, the test will be aborted.
> Added TimeSyncNTP exit condition

- WS2012R2/lisa/setupscripts/NET_Add_Max_NIC.ps1
- WS2012R2/lisa/setupscripts/NET_MAX_NIC.ps1
Due to a know issue which is affecting WS 2012, max synthetic NICs is
now limited to 3 NICs on this host version
> NET Max Synthetic NICs - Additional host check added

- WS2012R2/lisa/remote-scripts/ica/NUMA_off_kernel.sh
Fix a minor bug:
The grub2 config file on gen2 for fedora is  /boot/efi/EFI/fedora/grub.cfg, so make the config file as a variable
> NUMA_off_kernel.sh: update rhel grub2 config file

- WS2012R2/lisa/remote-scripts/ica/STOR_VSS_Disk_Stress.sh
Minor bug fix to get $DISTRO, without "*", cannot match to "Red*Hat*".
> Minor update SToR_VSS_Disk_Stress to get DISTRO

- WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
DM_CONFIGURE_MEMORY.ps1 was not setting DM values on dependency VMs  and
this caused most of the tests to fail.
> Dynamic Memory: Setupscript fix

- WS2012R2/lisa/xml/SR-IOV.xml
Due to an issue showing up on SR-IOV when using a VM with 32+ vCPUs and
7 SR-IOV NICs, we're adding a new TC for this particular case.
-Create a Linux VM and configure it with the Max number of synthetic NICs
(7 NICs) and Max number of vCPUs allowed by host/vm generation.
-Configure SR-IOV on each NIC.
-Verify network connectivity over each SR-IOV device.
> SR-IOV: New TC - Max NICs with Max vCPUs

- WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
On RHEL and Centos the network service must be restarted before pinging an IPv6 address.
> Fixed Legacy NIC test case

- WS2012R2/lisa/xml/NET_Tests_IPv6.xml
Removed the MAC address parameter from the XML file in order to use the random generated one.
> Fixed CopyLargeFile test

- WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
We will now skip VLAN Trunking TC on RHEL/CentOS 6.6 and lower because
the feature is unsupported
> VLAN Trunking: Added skipped state for RHEL/CentOS 6.6 and lower

- WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1
In case the host had already a partition with the same name, the script
would exit with an error. Added a check for this. If a partition exists,
the script now will dismount the vhd file and then will proceed with the
testing.
> Heartbeat_PausedCritical TC fix

- WS2012R2/lisa/remote-scripts/ica/STOR_VSS_Set_VSS_Daemon.sh
- WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Change_Hypervvssd.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Disable_Enable_VSS.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Stop_VSSD.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/STOR_VSS_Backup_Tests.xml
Add one case about backup when vss is disabled and enabled in the "integration service", if VSS is disabled, it should do offline backup, otherwise do online backup.
Note: Refer to bug https://bugzilla.redhat.com/show_bug.cgi?id=1074407,  after kernel version kernel-3.10.0-383.el7, the check or un-check VSS could take effect without vm reboot.
Case Description: 
Check  'Backup(volume snapshot)' after un-check 'Backup(volume snapshot)' integration services from Hyper-V Manager and do backup after un-check and check
Test Steps:
1. Right click your VM in Hyper-V Manager, select ""Settings"", change to
""Integration Services"" and un-check ""Backup (volume snapshot)"""
2. Backup VM from server host
3. Change to ""Integration Services"" from Hyper-V Manager settings and check
""Backup (volume …
> Add vssd disable enable vssd

- WS2012R2/lisa/remote-scripts/ica/NET_MAX_NIC.sh
Remove TestConnection ping external network checking when adding multiple NICs in the same virtual switch. Refer to closed bug https://bugzilla.redhat.com/show_bug.cgi?id=1391666.
> Update NET_MAX_NIC to remove TestConnection check

- WS2012R2/lisa/setupscripts/InjectIPconstants.ps1
- WS2012R2/lisa/xml/NET_Tests.xml
add one parameter about remote_sever to support change remote server ip, 8.8.4.4 could not ping successfully sometimes in Beijing, if not set the parameter, default is 8.8.4.4.
> Update InjectIPconstants default server as 8.8.4.4 and support parameter

- WS2012R2/lisa/setupscripts/Kdump.ps1
when execute Crash_single_core, it always abort after trigger kdump, but the kdump_results cannot be executed. It is caused that "plink.exe 'echo c > proc/sysrq-trigger 2>/dev/null &'" could not exit.  In other words, if run this command in powershell terminal,  it stucks in the terminal, if press "enter", it will exit with error "lost network connect".
This change is use Start-Process and no "Wait" parameter.
> Fix kdump case single core always abort by use start-process

- WS2012R2/lisa/remote-scripts/ica/Kdump_Results.sh
- WS2012R2/lisa/xml/Kdump_Tests.xml
Locally we use the same xml for all the cases, for this private key, in Network_Tests.xml, the private key is SSH_PRIVATE_KEY, in the kdump_tests.xml, it use ssh_key, so make them keep consistent.
> Minor change kdump private key name from sshkey to ssh_private_key

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
- WS2012R2/lisa/remote-scripts/ica/Kdump_Execute.sh
- WS2012R2/lisa/remote-scripts/ica/Kdump_Results.sh
- WS2012R2/lisa/remote-scripts/ica/Kdump_nfs_config.sh
- WS2012R2/lisa/setupscripts/Kdump.ps1
1. Support fedora distro
2. Kdump_Config.sh
- Improve grub config file to use $(find /boot -name grub.cfg)
- Return Skipped if crashkernel=auto for fedora
3. Kdump_Execute.sh: For nfs, it needs more than 50 seconds to start kdump, so add while to check kdump service status is active
4. Kdump.ps1: If config script returns Skipped, then exit the case and print the skip log
> Kdump add fedora

- WS2012R2/lisa/remote-scripts/ica/NET_Corruption.sh
- WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/setupscripts/NET_HotAddMultiNIC.ps1
- WS2012R2/lisa/setupscripts/NET_HotAddRemoveNIC.ps1
- WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
Mainly fix fedora test error in network cases:
ChangeNetTypeGuest,CopyBothWayss,VlanTagging,VlanTrunking,Network_Hang_Vxlan,TCP_Corruption,HotAddMultiNIC,HotAddRemoveNic,HotAddRemoveMaxNic by add "Fedora" distribution and add sleep time.
> Update Network related script to support fedora test

- WS2012R2/lisa/setupscripts/Production_checkpoint_partition.ps1
In case the TC specifies that a VHD disk has to be added to the VM
and the VM is a gen2, skip TC.
> Added Skip TC on gen2 VM if IDE controller is used

- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
Minor update SROR_VSS_BackupRestore_ISO_NoNetwork case
1) after send "at -f runtest.sh now + 1 minutes" by plink, it gets error "Error:Unable to submit runtest.sh to the vm", so ignore the return value checking, it could be covered by pingresult checking.
2) Extend the Start-sleep -Seconds 65 to check the network status
3) WaitforVMToStartKVP failed in Fedora, so update to WaitforVMToStartSSH.
> Minor update STOR_VSS_BackupRestore to make case more stable

- WS2012R2/lisa/setupscripts/SR-IOV_GetMLNXInfo.ps1
The MLNX module does not appear if it is not imported before running
the Import-Module cmdlet. Fixed usign ListAvailable parameter.
> Fixed Get-Module cmdlet

- WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
- WS2012R2/lisa/setupscripts/DM_CleanShutdown.ps1
- WS2012R2/lisa/setupscripts/DM_HighPriority.ps1
- WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_Stress_ng.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_stressapptest.ps1
- WS2012R2/lisa/setupscripts/DM_MaxMemHonor.ps1
- WS2012R2/lisa/setupscripts/DM_MinMemHonor.ps1
- WS2012R2/lisa/setupscripts/DM_PressureChangesDemand.ps1
- WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
- WS2012R2/lisa/setupscripts/DM_SaveRestore.ps1
- WS2012R2/lisa/setupscripts/DM_StartupLowCompete.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/DM_Tests.xml
- Separate Hot Add tests into 3 categories:
1. **Basic Hot Add tests** – Tests which use only one VM – Adding 128MB
chunks every 10 seconds. If these tests fail, then we know it’s an issue
with the test VM.
2. **Complex Hot Add tests** – Tests which use 2 VMs – Adding 128MB chunks
every 10 seconds. These tests may fail due to other VMs
running/starting/stopping on the host or problems with the Dependency
VM.
3. **Stress Hot Add tests** – 3 new TCs. One will add 512MB chunks every 5
seconds and other will add 512MB chunks every second. The last one will stress the
VM with 8GB of memory instantly. This will probably cause failures on WS2012 
and WS2012R2 but may pass on WS2016
- Fixed an issue where an error occured on DM_Configure_Memory.ps1 when
allocating memory to the VM
- Moved …
> Dynamic Memory - New TCs, code cleanup & improvements

- WS2012R2/lisa/remote-scripts/ica/perf_iperf_client.sh
- WS2012R2/lisa/remote-scripts/ica/perf_iperf_server.sh
- WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
- WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
- WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
- WS2012R2/lisa/setupscripts/perf_SRIOV_enable.ps1
- WS2012R2/lisa/tools/middleware_bench/AWS.py
- WS2012R2/lisa/tools/middleware_bench/connector.py
- WS2012R2/lisa/tools/middleware_bench/db_utils.py
- WS2012R2/lisa/tools/middleware_bench/results_parser.py
- WS2012R2/lisa/tools/middleware_bench/tests/run_network.sh
Update perf ntttcp and iperf to use a single script w/o sriov. Makes use of an xml specified parameter to do the configurations:
- SRIOV=no (simple config)
- SRIOV=yes (config sriov using transparent-vf)
- SRIOV=bond (config sriov using bondvf.sh)
Also moved all script dependencies to perf_utils in order to avoid circular imports and adjusted function parameters.
> Perf utils update for transparent vf

- WS2012R2/lisa/lisa.ps1
- WS2012R2/lisa/stateEngine.ps1
1. Added functionality for the "onError" tag in DoDiagnoseHungSystem
state. This feature worked only when a running test entered
failed/aborted state. Sometimes the VM enters aborted state because it's
not booting and this fix is covering this scenario.
2. Reverted lisa exit code because Jenkins jobs no longer catch lisa
fails
> Minor changes to lisa behavior

- WS2012R2/lisa/remote-scripts/ica/install_lis_next.sh
The "custom_lis_next" parameter was added in order to enable installation of lis-next from local folder, without cloning it from a remote repository.
The new parameter contains the path to the custom lis-next build.
> Added a new parameter to skip clone step

- WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Mount_Multi_Paths.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Mount_Squashfs.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Change_Hypervvssd.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Backup_Disable_Enable_VSS.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
A new step was added in the Logger class in order to log messages in the test summary file. In the new behavior, time-stamped messages are directed towards the standard output and the test summary file whereas the logs directed towards the general summary file are not time-stamped.
The Logger class was moved into a separate file in order to avoid missing variables errors from TCUtils.ps1 and a GetLogger static method has been added in order to abstract the process of parsing testParams and creating the log file names. 
Test scripts that contained logger code (VSS Tests) have been updated on the new behavior.
> Added logging to test case file

- WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
- WS2012R2/lisa/setupscripts/NET_MAX_NIC.ps1
Newer kernels don't configure tulip driver and a check is needed for it
> Added check for tulip driver

- WS2012R2/lisa/remote-scripts/ica/BuildKernelWithPatches.sh
Recent linux-next builds require elfutils packages to compile
> Added new packages in BuildKernelWithPatches.sh

- WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
- WS2012R2/lisa/setupscripts/DM_CleanShutdown.ps1
- WS2012R2/lisa/setupscripts/DM_DISABLE.ps1
- WS2012R2/lisa/setupscripts/DM_HighPriority.ps1
- WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_Stress_ng.ps1
- WS2012R2/lisa/setupscripts/DM_HotAdd_stressapptest.ps1
- WS2012R2/lisa/setupscripts/DM_MaxMemHonor.ps1
- WS2012R2/lisa/setupscripts/DM_MinMemHonor.ps1
- WS2012R2/lisa/setupscripts/DM_PressureChangesDemand.ps1
- WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
- WS2012R2/lisa/setupscripts/DM_SaveRestore.ps1
- WS2012R2/lisa/setupscripts/DM_StartupLowCompete.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/AllTests_Gen2VM.xml
- WS2012R2/lisa/xml/CoreTests.xml
- WS2012R2/lisa/xml/DM_Tests.xml
Orignial DM.xml includes VMName, which is used to define the test vmName and dependency vmName. Since two vms name can be defined in the VMs section, we could use and avoid defining them in the testParams section.
Also we run all the cases in one xml file, vmName and VM2Name are defined dynamically, it cannot change the DM.xml single case's parameter by automation, so submit this pull requests.
Thank you.
> Update DM related script to remove vm definition in case xml parameter

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_fileCopy.sh
Test gave unnecessary fails due to incorrect packet count measurement.
Now it verifies how many interfaces receive/transmit packets. For every
interface tested, this has to increase
> SR-IOV Multiple FileCopy fix

- WS2012R2/lisa/xml/CoreTests.xml
update CheckNuma_Maximum in coreTests.xml for startupMem:
1) remove staticMem=2048MB,  ChangeCPU, DM_Disable or DM_Cofig_Memory,NUMA.ps1, no file to parse this staticMem
2) add startupMem=2048 for CheckNuma_Maximum, change DM_Cofig_Memory to set up startupMem.
note: NumaNodes name is a little confusing, I want to update it, but too many files use ChangeCPU.ps1 :)
Just find this issue since before our test machines by default using 2048 as memory, after set new vm as 4G as default, get the error.
> Minor update CheckNuma_Maximum in coreTests.xml for startupMem

- WS2012R2/lisa/setupscripts/CreateGcovReport.ps1
A new automation script was added in order
to integrate the process of generating and
collecting code coverage html reports into
LISA.
The test script uses .gcov files in order
to generate the final report. The location of
the files can be specified in the $reportsFolder
parameter.
> Add script to collect coverage reports

- WS2012R2/lisa/setupscripts/Shielded_TDC.Tests.ps1
- WS2012R2/lisa/setupscripts/Shielded_TDC.ps1
- WS2012R2/lisa/setupscripts/Shielded_template_prepare.ps1
- WS2012R2/lisa/xml/Shielded_PreTDC.xml
>>These are test scripts that must be used with pester -
Tests included:
--LSVM-TDC-01: Run the TDC wizard with a Linux VHDX file.
--LSVM-TDC-02: Verify the output LSVM VHDX file from the TDC Wizard.
--LSVM-TDC-03: Verify a VHDX file that has not had lsvmprep run fails
TDC
--LSVM-TDC-04: Test TDC using Linux VHDX file and an invalid certificate
>>Also added post testing preparation for TDC 
TDC needs the VM to be corectly configured - no checkpoints and first boot option
set to hard drive. A copy of the vhdx is also made for later use.
>  Shielded VMs testing: Added TDC test cases

- WS2012R2/lisa/setupscripts/Shielded_PRO.Tests.ps1
- WS2012R2/lisa/setupscripts/Shielded_PRO.ps1
-These are test script that must be used with pester -
Tests included:
--LSVM-PRO-01: Verify a provisioned Linux Shielded VM boots
successfully.
--LSVM-PRO-02: Modify VSC, verify a VM created from the Linux VHDX
template fails provisioning
--LSVM-PRO-03: Modify file in boot partition of Linux VHDX template and
verify provisioning fails.
--LSVM-PRO-04: Modify file in root partition of Linux VHDX template and
verify provisioning fails
--LSVM-PRO-05: VM fails to boot if the specialization file has been
modified.
--LSVM-PRO-06: Unsupported specialization items are logged
> Shielded VMs testing: Added Provisioning test cases

- WS2012R2/lisa/xml/SR-IOV.xml
Due to recent failures, a TC that tests SR-IOV with only 1 vCPU is needed
> SR-IOV: Added 'One vCPU' TC

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_UpgradeKernel.sh
- WS2012R2/lisa/remote-scripts/ica/shielded_deployed_functions.sh
- WS2012R2/lisa/setupscripts/Shielded_DEP.Tests.ps1
- WS2012R2/lisa/setupscripts/Shielded_DEP.ps1
- WS2012R2/lisa/setupscripts/Shielded_PRO.ps1
Shielded VMs testing: Added Deployed VMs test cases
- These are test scripts that must be used with pester-
Tests included:
-- LSVM-DEP-01: Update the kernel on a LSVM and verify the VM continues to boot successfully
-- LSVM-DEP-02: Update a boot component on a LSVM and verify the VM boots successfully.
-- LSVM-DEP-03: Clone a Linux Shielded VM VHDX and confirm it fails to boot.
-- LSVM-DEP-04: Verify well known DMCrypt/LUKS passwords no longer work
-- LSVM-DEP-09: Online Backup/Restore a data disk on a Linux Shielded VM
-- LSVM-DEP-10: Online Backup, then Restore the system disk of a Linux Shielded VM
-- LSVM-DEP-12: Add COM port to LSVM
-- LSVM-DEP-13: Attack a VHDX file of a functioning LSVM
-- LSVM-DEP-16: Disable Secure Boot and verify Linux Shielded VM fails to boot
> Shielded VMs testing: Added Deployed VMs test cases

- WS2012R2/lisa/setupscripts/STOR_VHDXResize_Basic.ps1
- WS2012R2/lisa/setupscripts/STOR_VHDXResize_DiskOver2TB.ps1
- WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
- WS2012R2/lisa/xml/STOR_VHDXResize.xml
Minor updates:
1) update host storage size flag from 50GB to 20GB, since our test host has less storage, if the limitation set  as 50GB, storage resize related test cases will fail. Have check resize related test cases, generally it will change from 3G size to 4G. For 2304GB, if it is format as ext4, disk size is about 1.1G, if set as ext3, disk size will be 150G, here ignore ext3 file system.
In the file STOR_VHDXResize_PartitionDiskOver2TB.sh line 129, if it could mkfs successfully, will break the look, so it only test ext4 here. 
2)  Remove the ext3 from the xml when resize more than 2T.
3) Minor update logger.info from logger.error for "Restore duration" information for backup test case.
> Update storage resize limiation for host from 50G to 20G

- WS2012R2/lisa/remote-scripts/ica/NET_COPY_LARGE.sh
In case of IPv6 testing of CopyLargeFile a Private network is used
and SCP has to be forced to use the addapter connected to that
network. Otherwise the external network might be used, resulting in
test failure.
> Fixed CopyLargeFile TC for IPv6

- WS2012R2/lisa/remote-scripts/ica/Hyperv_Daemons_Files_Status.sh
"Check_HypervDaemons_Files_Status" case failed on RHEL6.9
The script was looking for "xxx.service" for hyperv daemons on rhel6, but rhel6 does not use systemctl. Unsurprisingly, case failed. I don't know why this happens since this is not a new case. Probably nobody used it on rhel6.
This patch worked for me
> Fix bug: Not looking for right hyperv daemon files on RHEL6

- WS2012R2/lisa/setupscripts/Kdump.ps1
- WS2012R2/lisa/xml/Kdump_Tests.xml
In case of external Kdump usage, the time needed to create the vmcore
file is bigger, and the automation needs to wait accordingly.
> Increased Kdump TC timeout values

- WS2012R2/lisa/setupscripts/FCOPY_large_file.ps1
- WS2012R2/lisa/xml/FCOPY_Tests.xml
If the param not set in xml, file size will be 10GB by default.
> Add param "Large_File_Size_GB" for FCOPY_large_file case

- WS2012R2/lisa/stateEngine.ps1
Stop all remaining processes opened by the Powershell console after
the tests have finished running.
> Kill remaining processes after testing is done

- WS2012R2/lisa/remote-scripts/ica/NET_MAX_NIC.sh
- WS2012R2/lisa/xml/STOR_VSS_Backup_Tests.xml
MaxNIC,MaxLegacyNIC,MaxSyntheticNIC all use file NET_MAX_NIC.sh, after ifup ethX, it also needs a while to get gateway. so add sleep for a while before CheckGateway to make cases more stable.
> Minor update NET_MAX_NIC by adding sleep time after ifup

- WS2012R2/lisa/setupscripts/VMBus_PanicNotifier.ps1
There are cases when the VM would not reboot after triggering the
crash and remain in an hanging state. To avoid this behavior we
TurnOff the VM after testing is done.
> Updated TC to turnoff the VM

- WS2012R2/lisa/xml/KvpTests.xml
If the VM does not reboot after testing the rescind issue and the
issue is present, the following test scenarios will be also affected.
> Updated KVP XML file to reboot after Rescind test

- WS2012R2/lisa/lisa.ps1
There are cases when some processes remain hanging after the testing
is done. In those cases lisa will stop the remaining processes.
> Stop remaining child processes

- WS2012R2/lisa/remote-scripts/ica/lsvmbus_basic.sh
- WS2012R2/lisa/xml/lsvmbus.xml
The generation info for lsvmbus-basic case is manually defined in xml.
This patch make the shell script detect vm generation automatically.
> Auto detect vm generation in lsvmbus-basic

- WS2012R2/lisa/setupscripts/TCUtils.ps1
GetVMFeatureSupportStatus() would return wrong value in specific
condition. eg. feature is supported in version "3.3.3-3", current
kernel version is "3.4.2-3", function would return $false, which is
obviously incorrect.
> Fix bug: GetVMFeatureSupportStatus() potential incorrect return value

- WS2012R2/lisa/remote-scripts/ica/Hyperv_Daemons_Files_Status.sh
- WS2012R2/lisa/remote-scripts/ica/UIO_Basic.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/xml/UIO_Tests.xml
This test covers basic operations of uio and uio_hv_generic:
1. loading/unloading uio & uio_generic for 100 times
2. assign a device (network adapter) to uio_hv_generic
Manal test steps:
1. setup another network adapter for the vm
2. Load uio, check it is loaded
\# modprobe uio
\# lsmod |grep uio
3. Unload uio, check it is unloaded
\# modprobe -r uio
\# lsmod |grep uio
4. Load uio_hv_generic, check uio & uio_hv_generic are loaded
\# modprobe uio_hv_generic
\# lsmod |grep uio
5. Add new id (ClassID) to uio_hv_generic
\# ip addr
( Use new network adapter for the ehtx in following commands )
\# ClassID=`cat /sys/class/net/ethx/device/class_id |awk '{ print( substr($1, 2, length($1)-2)) }'`
\# echo $ClassID > /sys/bus/vmbus/drivers/uio_hv_generic/new_id
6. Deassign the device from kernel …
> Add UIO test case - UIO_Basics

- WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1
In case the script is being run remotely, the computername parameter is required.
> Added computername parameter to cmdlet

- WS2012R2/lisa/setupscripts/STOR_unPlug_Plug.ps1
When testing on the rhel 7.5 gen2 vm, get the $error information: how the WARNING: fdisk GPT support is currently new, and therefore in an experimental phase. 
so firstly do $error.Clear() then do  Add-VMHardDiskDrive and  Remove-VMHardDiskDrive to avoid other warning inducing test case failure.
> Minor update STOR_unPlug_Plug error.clear position

- WS2012R2/lisa/remote-scripts/ica/lis_install.sh
Some times wget might append the token at the end of the file name.
This is resolved by using -O flag with the actual file name as a value.
> lis_install.sh - code fix

- WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
The patch 1406f1b #915 is bringing back a issue fixed in patch 16d1884 #905 .
eg. Feature is supported in version "3.3.3-3", current kernel version is "3.2.4-3", function would return $True, which is incorrect.
> Fix: TCUtils.ps1: GetVMFeatureSupportStatus wrong return value

- WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_GrowFSAfterResize.sh
We have been testing resize cases on RHEL6, on which xfs tools are not present.
There is actually some script trying to skip xfs in this circumstance, but it does not work correctly.
> GrowFSAfterResize: skip xfs test when xfs tools not present

- WS2012R2/lisa/stateEngine.ps1
The state file should be unique per VM.
If multiple test suites are run for multiple VMs, a conflict might appear in the state.txt file, which now we make unique for each VM.
Linux VM state.txt remains unchanged.
> VM state file separation

- WS2012R2/lisa/setupscripts/KVP_Max_Read.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
KVP_Max_Read: skip test if kernel version is below 3.10.3.860 (RHEL7.5)
This version is not official release version yet, might need to update later
Some modification in function GetVMFeatureSupportStatus, makes it support both format like "10.3.0.1" and format like"10.3.0-1"
>  KVP_Max_Read: skip kernel version below 3.10.3.860 (RHEL7.5)

- WS2012R2/lisa/setupscripts/INST_LIS_TimeSyncServiceDisableEnable.ps1
- WS2012R2/lisa/setupscripts/Kdump.ps1
1. For case Crash_NMI, get the error message as below, rerun pass, considering add more sleep here to make it robust.
Creating Log File for : setupscripts\kdump.ps1
Rebooting the VM.
Waiting the VM to have a connection...
Error: Configuration is not correct. Check logs for details.
False
2. For test case INST_LIS_TimeSyncServiceDisableEnable.ps1, get failure as below, rerun pass, add sleep before save-vm to make it more robust.
Creating Log File for : setupscripts\INST_LIS_TimeSyncServiceDisableEnable.ps1
The operation on computer '2016-auto' failed: Provider load failure 
Parsing testParams
Info : Verify the Integrated Services Time Sync Service is enabled
Info : Disabling the Integrated Services Time Sync Service
Info : Integrated Time Sync Service successfully disabled
Info : Enabling …
> Minor update sleep time make case more robust

- WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh
The case is not strictly stable, this might help enhance stability.
Tested running with this patch for more than 10 times, all passed.
> HotAddRemoveNIC: sleep 5sec after ifup

- WS2012R2/lisa/setupscripts/CreateVMs.ps1
This change is fixing an issue with CreateVMs - in some ocasions it
failed if it was run on a node that was part of a failover cluster.
> CreateVMs.ps1 small fix

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
- WS2012R2/lisa/setupscripts/Kdump.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
Extra kdump config is required on WS2012, while previous extra config
does not work for WS2012 host.
Test-NetConnection does not work for WS2012, use function
WaitForVMToStartSSH in TCUtils instead.
> Kdump: support testing RHEL6/7 on WS2012

- WS2012R2/lisa/setupscripts/deploy_scenarios_pipeline.ps1
CentOS/Oracle/RHEL 6.x did not have kvp running after a kernel upgrade
(expected behavior), but the script was looking for kvp data. Making
this optional
> deploy_scenarios_pipeline.ps1 kernel upgrade fix

- WS2012R2/lisa/Infrastructure/aio.sh
In some cases the firewalld service can interfere with the automated
testing.
> Disable firewalld service for RedHat 7

- WS2012R2/lisa/remote-scripts/ica/UIO_Basic.sh
I used wrong function for the skipping, my apologies.
> UIO: fix unable to skip case for low kernel version

- WS2012R2/lisa/remote-scripts/ica/modules_check.sh
This commit fixes the way modules_check.sh checks for the init
image. Instead of having one 'IF' structure with multiple conditions
chained with logical 'OR' operators, the check is done using
multitple 'IF' instructions.
This prevents the error showing up in the log, in case the first
condition isn't true.
> Fixed the init image check

- WS2012R2/lisa/remote-scripts/ica/Kdump_Results.sh
If there is more than one file with size over 10MB, the array index
doesn't point to the exit code. Changed the code to use the last
element of the array for status checking.
> Fix Kdump results checking on NFS

- WS2012R2/lisa/tools/middleware_bench/report/results_parser.py
- WS2012R2/lisa/tools/middleware_bench/tests/run_orion.sh
- WS2012R2/lisa/tools/middleware_bench/tests/run_postgresql.sh
- WS2012R2/lisa/tools/middleware_bench/tests/run_terasort.sh
- WS2012R2/lisa/tools/middleware_bench/utils/setup.py
Fix case issues for 
•test_postgresql
•test_orion_raid
•test_terasort
•test_zookeeper (only fail against AWS)
•test_terasort on AWS platform need interaction when run command apt upgrade -y procps
> Fix test cases for middleware_bench

- WS2012R2/lisa/remote-scripts/ica/NET_Configure_Vxlan.sh
- WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1
Disabling firewalld for RHEL in case it is running when configuring
the VxLAN interface. Reduced the wait time for rsync to transfer the
files because in some cases the connection would drop if the value
is too big.
> Update Net_Hang_VxLAN TC

- WS2012R2/lisa/setupscripts/SR-IOV_enable.ps1
- WS2012R2/lisa/xml/SR-IOV.xml
The vSwitch name will now be a param in the xml file
> SR-IOV: Removed hardcoded vSwitch name

- WS2012R2/lisa/remote-scripts/ica/STOR_NFS_Client.sh
We have been running multiple lisa runs simultaneously. This scrip
create test files under same name and clears everything on the nfs
mount point after test. This patch avoids this kind of conflicts.
> STOR_NFS_Client.sh: Use random file name to avoid conflicts

- WS2012R2/lisa/setupscripts/ChangeCPUIterated.ps1
- WS2012R2/lisa/xml/lis_pipeline_bvt.xml
1. Changed noReboot flag of VerifyIntegratedTimeSyncService TC from True
to False
2. Multi_Cpu_Test is now updating the ipv4 after a reboot to avoid
issues with ipv4 change
> Core Tests: Automation tweaks

- WS2012R2/lisa/remote-scripts/ica/SR-IOV_DisableVF.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_MaxNIC.sh
- WS2012R2/lisa/remote-scripts/ica/SR-IOV_ModuleReload.sh
- WS2012R2/lisa/remote-scripts/ica/utils.sh
- WS2012R2/lisa/setupscripts/SR-IOV_Deattach_NIC.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_DisableNIC.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_Host_Disable.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_Ping_DisableVF.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_SavePauseVM.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_Stress_SavePause.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_iPerf_DisableVF.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/SR-IOV.xml
In some kernels, failback and max NICs TCs triggered a call trace
that wasn't logged. This adds a check for this.
> SR-IOV: Call trace check for various TCs

- WS2012R2/lisa/Infrastructure/aio.sh
In some cases the at daemon isn't installed by default and needs to
be installed. Moved the at daemon enabling command after installation.
> Enable atd daemon after install

- WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
Skipping Heartbeat_PausedCritical TC on WS2012. Changed GetParentVHD
to use GetVMGeneration method for better VM generation handling.
> Skip Heartbeat_PausedCritical on WS2012

- WS2012R2/lisa/stateEngine.ps1
When starting a preTest script, console output would be like
"starting preTest script System.XML.XmlElement"
If VM become unable to start after running setupScript, test case
name in test result will be set to "System.XML.XmlElement"
> stateEngine: Fix two incorrect xml references

- WS2012R2/lisa/tools/middleware_bench/providers/azure_service.py
- WS2012R2/lisa/tools/middleware_bench/suites/middleware.py
1 Azure side, before the used image benchcraftsqlserverwin2016 already install custom script, it caused the extension can't rerun, I recreate an image named benchcraftsqlserverwin2016test
2 Not use fixed vm name, update the parameter for custom script extension, otherwise winrm can’t work
> Fix case test_sql_server_inmemdb.

- WS2012R2/lisa/setupscripts/HV_Sock_Basic.ps1
- WS2012R2/lisa/xml/HV_Sock.xml
* Split the two parts of the HV_Sock_Basic TC into distinct tests
* Replaced Passed variable with True because lisa.ps1 would exit
when it would encounter a Passed variable and the second part would
not be tested
* Added a check to see if the binary file is already compiled on the
VM. This is needed for internal testing and it will not interfe with
the normal run of the test.
* Improved error logging for easier debugging.
> Hv_Sock refactorig

- WS2012R2/lisa/DebugScript.ps1
- WS2012R2/lisa/lisa.ps1
- WS2012R2/lisa/stateEngine.ps1
- WS2012R2/lisa/utilFunctions.ps1
Test scripts/setup scripts/cleanup scripts are designed to run in
background jobs, which makes debugging quite difficult. This new feature
allows user to print call trace and variable trace, or set break points
at specific lines/variables/commands/functions.
Example I: Print call trace for all background powershell scripts.
>lisa.ps1 run xml\HV_Sock.xml -debugScript All
Example II: Print both call trace and variable (trace level 2).
>lisa.ps1 run xml\HV_Sock.xml -debugScript All -traceLevel 2
Example III: Debug a specific script
>lisa.ps1 run xml\HV_Sock.xml -debugScript .\setupscripts\HV_Sock_Basic.ps1
Example IV: Set breakpoint at lines
>lisa.ps1 run xml\HV_Sock.xml -debugScript .\setupscripts\HV_Sock_Basic.ps1 -breakLine 53, 93
Example V: Set multiple breakpoints
>lisa.ps1 run …
> Add new feature: debugScript

- WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
- WS2012R2/lisa/xml/NET_Tests.xml
Modified Multicast TC to use CreateIfupInterface instead of the
script to set the static IP on the interface and stop the dependency
VM after the test has finished executing.
> Update Multicast TC

- WS2012R2/lisa/remote-scripts/ica/lis_install.sh
The removed wget check gave a false positive on 6.x centos/rhel versions
> lis_install.sh - removed check that failed on 6.x

- WS2012R2/lisa/setupscripts/RevertSnapshot.ps1
When running the full test suite additional snapshots get created
enven if they already exist. This causes the Restote-VMSnapshot
commandlet to receive a System.Object[], list that contains more
than a a single snapshot. This, in turn, causes all the tests that
use the RevertSnapshot.ps1 setup script to fail.
This commit fixes that issue.
> Quick fix for reverting snapshot issue

- WS2012R2/lisa/setupscripts/HV_Sock_Basic.ps1
- WS2012R2/lisa/setupscripts/SR-IOV_GetMLNXInfo.ps1
We currently use kerberos authentication in AD, If LISA is run inside a
PSSession, creating a new pssession in the test would require delegation
configured (and even it is configured, double hop to localhost is not
allowed). This patch use fresh identity to create PSSession instead of
using delegation (only if $env:HostUser and $env:HostPassword are defined,
otherwise the behaviour is not changed).
Our case is that our CI uses PSSession to connect to test host and run lisa. Creating a PSSession in the test case would results in this the kerberos double hop issue. And delegation does not work correctly with PSSession to "localhost". This patch is the best solution I can find, otherwise we will need to do modification on the framework to allow passing credential, which is quite a lot more …
> New-PSSession: Work around "Kerberos Double Hop" issue

- WS2012R2/lisa/remote-scripts/ica/Core_Config_TimeSync.sh
An attempt to install chrony will be made only if chrony is missing from
the system.
> CORE Timesync: Added check for chrony

- WS2012R2/lisa/remote-scripts/ica/Core_LIS_CD.sh
- WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1
- WS2012R2/lisa/xml/CoreTests.xml
Created this case based on bug https://bugzilla.redhat.com/show_bug.cgi?id=1338687
[Hyper-V][RHEL 7.2] storvsc messages for CD-ROM medium not present - tray closed
Test steps:
Create a Generation 2 VM
Start VM, add a dvd drive to scsi controller(ISO attached or not)
Check dmesg log to make sure it does not have multiple "medium not present" log, and add the call trace check.
> Add new test case for hot add dvd

- WS2012R2/lisa/xml/NET_LIVEMIG.xml
Added missing generation tag for LiveMigration XML.
> Fix LiveMigration for generation 2 VMs

- WS2012R2/lisa/remote-scripts/ica/utils.sh
Fixed detection of centos 5.x/7.5 in GetDistro
> Fix check for centos 5.x/7.5 detection

- WS2012R2/lisa/xml/STOR_VHDX.xml
Due to duplicate line of defaultSnapshot tag LISA would search for
"ICABase ICABase" snapshot name.
> Small XML fixes

- WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1
The yum command used to check for fedora based distributions returns
an error message on other distributions. Redirecting the stderr to
/dev/null to remove the error message.
> Remove error message for KVP TestRescind TC

- WS2012R2/lisa/remote-scripts/ica/FC_WWN.sh
- WS2012R2/lisa/remote-scripts/ica/FC_disks.sh
- WS2012R2/lisa/setupscripts/FC_AddFibreChannelHba.ps1
- WS2012R2/lisa/setupscripts/FC_WWN.ps1
- WS2012R2/lisa/xml/FC_Tests.xml
Based on existing FC two test cases, FC_WWN_Basic and FC_Disks_Detection to add two new test cases, including FC_WWN_Basic_Multi_Adapters and FC_Disks_Detection_Multi_Adapters.
1.  FC_Disks_Detection_Multi_Adapters -- since the vm can add 4 FC adapters as maximum number, locally we have case to cover this test point, add new case here.
2.   FC_WWN_Basic_Multi_Adapters -- this is based on bug https://bugzilla.redhat.com/show_bug.cgi?id=1308632,  check /sys/class/fc_host/hostx,  already have auto case FC_WWN_Basic to cover one adapter, locally we have test case to cover multiple adapters. 
Any comment or suggestion, will update.
Best Regards,
Xuemin
> Update FC_Tests.xml to support multiple fc adapters

- WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1
- WS2012R2/lisa/setupscripts/NET_ipinjection.ps1
- WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
Minor update existing test cases KVPTestRescind and NET_ipinjection to add the selinux log check, refer to https://bugzilla.redhat.com/show_bug.cgi?id=1347659, after enable/disable kvp and do ip-injection, then check ausearch -m avc and ausearch -m user_avc. The original bug reproduce rate is not 100%, here only cover the test scenario, but not same steps with the bug's steps.
Meanwhile, only move original script out of checkVM's else branch for KVPTestRescind.ps1, not change the script itself.
> Update KVP_TestRescind and NET_ipinjection for selinux check

- WS2012R2/lisa/remote-scripts/ica/KVP_BasicTest.sh
- WS2012R2/lisa/xml/KvpTests.xml
- WS2012R2/lisa/xml/RDOS_WS2012.xml
…of check
Update existing ReadKVPData_BasicTest test case, locally we have manual test cases: 
1. check hypervkvpd pool file directory and file permission
#ls /var/lib/hyperv/.kvp_pool_*
2.  check number of opened file descriptors by hypervkvpd  #lsof \|grep -c kvp 
 check the number of process two minutes later #lsof \| grep -c kvp
Refer to bug https://bugzilla.redhat.com/show_bug.cgi?id=949664.
3. After RHEL7.3, ls -la /proc/`pidof hypervkvpd`/fd \| grep hv_kvp 
This case includes more test points, any comment, suggestions will update. Thank you so much.
  
 
> KVP basic test case - permissions and lsof checks additions

- WS2012R2/lisa/remote-scripts/ica/STOR_Large_Disk_CopyFile.sh
- WS2012R2/lisa/xml/STOR_VHDX.xml
RHEL7 Vm gets hung_task_timeout_secs and call trace when dd large file on nfs when testing on 2012R2 host.  Refer to https://bugzilla.redhat.com/show_bug.cgi?id=1457760, currently not get fix yet.
This PR replaces the dd command's parameter bs and count hard code to the xml config file, then it could input the smaller count number to make test case run stable.
Thank you.
> Minor update STOR_Large_Disk_CopyFile with parameter for dd

- WS2012R2/lisa/remote-scripts/ica/utils.sh
When test on the network vlanTrunking case, execute line #1225 of NET_VLAN_TRUNKING.ps1, it will call RemoveVlanInterfaceConfig, and it will restart network. Sometimes, after restart vm network, "plink.exe root@ip address" does not work in the powershell script, which induces the test case abort. (even can connect by plink in the other session, e.g. try on the other windows powershell)
In the utils.sh function RemoveVlanConfig, it already has #1124 line ip link set $interface.$vlanID down, so could remove "service network restart" line. If remove the service network restart line in vm, it does not have impact to the eth0 adapter, the plink connection will keep connected. 
> Update utils.sh for RemovevlanConfig by removing service network restart

- WS2012R2/lisa/setupscripts/Core_Time_VDSO.ps1
- WS2012R2/lisa/tools/time/gettime.c
- WS2012R2/lisa/xml/CoreTests.xml
Only support kernel newer than 3.10.0-862, refer to https://bugzilla.redhat.com/show_bug.cgi?id=1410023 (Bug 1410023 - [RFE][Hyper-V][RHEL7.5] vDSO support for hyperv_clocksource_tsc_page)
> Add vdso case

- WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/file_parser.py
ntttcp for linux tool v.1.3.4 has a new logging format, with multiple throughput fields.
Changing the parser to continue to use only the average throughput value.
> lisa-parser: Fixed regex for throughput

- WS2012R2/lisa/remote-scripts/ica/lsvmbus_basic.sh
- WS2012R2/lisa/remote-scripts/ica/lsvmbus_target.sh
1. From my test, the cpu count that attached to the network driver is less than 8, and the cpu count that attached to the scsi controller is (N+3)/4.
Not sure about the cpu count is right, the result is only the same as my test. If it is wrong, feel free to correct me. Thanks!
2. Add fedora support.
> lsvmbus: fix cpu count issue about network driver and scsi controller

- WS2012R2/lisa/setupscripts/CORE_max_cpus.ps1
Minor change: if $guest_max_cpus is larger than host supported locical cores, set $guest_max_cpus as maxCpus.
> Minor update CORE_max_cpus.ps1 to fix bug

- WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
Minor update kdump_config.sh to add hyperv_fb in the blacklist for hyper-v 2012 host.
If do not blacklist it, kdump will fail in the latest rhel.
> update Kdump_Config.sh for blacklist in hyper-v 2012 host

- WS2012R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
- WS2012R2/lisa/setupscripts/CORE_reload_modules.ps1
- WS2012R2/lisa/xml/CoreTests.xml
- WS2012R2/lisa/xml/StressTests.xml
- WS2012R2/lisa/xml/hyperv_bvt.xml
- WS2012R2/lisa/xml/hyperv_fvt.xml
- WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
- WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
- WS2012R2/lisa/xml/lis_pipeline_bvt.xml
- WS2012R2/lisa/xml/lis_pipeline_fvt.xml
- WS2012R2/lisa/xml/ubuntu_azure_kernel_fvt.xml
Hi Chris,
Currently there is one bug https://bugzilla.redhat.com/show_bug.cgi?id=1613655, if use original #100 times and sleep 1 for six times, it cannot catch the bug like https://bugzilla.redhat.com/show_bug.cgi?id=1613655, this case only reproduces on SMP, but not UP, so may need to add two cases. Do you want to change related cases.xml to add new test cases about StressReloadModules_UP and StressReloadModules_SMP? If yes, I will change it too?
> Update Core_StressReloadModules to deeper stress

- WS2012R2/lisa/remote-scripts/ica/utils.sh
Hi Chris,
Generally during testing, NetworkManager service is disabled, I see it disable in the aio.sh. In our local test, we disable NetworkManager too, most of our network test cases run as network status enabled 
If disable network service, only enable NetworkManager, it needs to remove "NM_CONTROLLED=no" line to make the NIC created successfully.
Related test cases:
GuestOnlyNetwork
ChangeNetTypeGuest
JumboFrame
VlanTagging
Note: VlanTrunking_ipv6 cannot pass if disable network and only NetworkManager enabled, I try using  "nmcli con add type vlan con-name VLAN20 dev eth0 id 20 ip6 xxxx" in createVlanConfig, still need debug, only share information.
> Update utils.sh CreateIfupConfigFile to remove NM_Controlled as No

- WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1
- WS2012R2/lisa/setupscripts/RemoveIsoFromDvd.ps1
- WS2012R2/lisa/xml/CoreTests.xml
- WS2012R2/lisa/xml/lis_pipeline_fvt.xml
No longer requires a CDTest.iso dependency file, the script will automatically download an ISO.
Fixed description for cleanup script, the test case actually is removing the DVD unit and not eject ISO only.
> CDmount test case refresh

- WS2012R2/lisa/setupscripts/deploy_scenarios_pipeline.ps1
This is a needed fix because CORE_LISmodules_version.sh was renamed to
CORE_LIS_modules.sh
> deploy_scenarios: renamed validation script

- WS2012R2/lisa/remote-scripts/ica/install_kernel.sh
grub-legacy-ec2 is breaking the kernel installation due to some incompatibility in kdump with recent kernels.
EC2 integration and support is not required, thus removing the package for easy fix.
> install_kernel: remove grub-legacy-ec2 on Debian

- WS2012R2/lisa/remote-scripts/ica/lsvmbus_target.sh
- WS2012R2/lisa/xml/hyperv_bvt.xml
- WS2012R2/lisa/xml/hyperv_fvt.xml
- WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
- WS2012R2/lisa/xml/lis_pipeline_bvt.xml
- WS2012R2/lisa/xml/lsvmbus.xml
Tested with 2 nics and without snapshot revert in setup phase : 
**Test lsvmbus_target            : Passed**
This script covers test case: lsvmbus-02
Counting the cores spread only for the first NIC...
Network driver is spread on 8 core(s) as expected, actual cpu count in os is '8'.
Storage driver is spread on all 2 core(s) as expected.
Test completed successfully.
> lsvmbus: Fix core spread issue 

- WS2012R2/lisa/remote-scripts/ica/modules_check.sh
On ubuntu distros the initrd image is made from 2 separate archives
(microcode & initrd) and the old unpacking failed. We skip the microcode
archive and unpack the actual initrd image.
> Fixed cpio unpacking for initrd TC

- WS2012R2/lisa/setupscripts/eventid_18602_regression.ps1
Change checking Wait-VMEvent method's return value directly as checking $resultEvent[-1].
After change write-host to write-output, it also changes the return value of Wait-VMEvent. So do minor change to fix this newly induced bug.
Thank you.
> Update eventid_18602_regression to fix return value bug

- WS2012R2/lisa/remote-scripts/ica/DM_Top_LoadAverage.sh
- WS2012R2/lisa/xml/DM_Tests.xml
This case covers bug https://bugzilla.redhat.com/show_bug.cgi?id=1065107, verify that load average value of top command is smaller than 1 when dynamic memory is enabled.
Test steps:
1. Enable dynamic memory with Hyper-V manager.
2. Start the guest, check the top metrics after waiting for several minutes.
#top
top - 14:31:23 up 6 min,  2 users,  load average: 0.00, 0.07, 0.05
Tasks: 267 total,   2 running, 265 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.3 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  1.3 si,  0.0 st
KiB Mem:   1406544 total,   468852 used,   937692 free,     1240 buffers
KiB Swap:  2129916 total,        0 used,  2129916 free.   176240 cached Mem
3. Check load average value of past minutes.
Verify results:
The load average value is smaller than 1.
> Add new balloon case about checking top load average value

- WS2012R2/lisa/remote-scripts/ica/check_traces.sh
- WS2012R2/lisa/setupscripts/DM_HotAdd_Eatmemory.ps1
- WS2012R2/lisa/setupscripts/TCUtils.ps1
- WS2012R2/lisa/xml/DM_Tests.xml
Add two test cases for eatmemory stress to cover https://bugzilla.redhat.com/show_bug.cgi?id=1361245 and regression bug https://bugzilla.redhat.com/show_bug.cgi?id=1662277, also do minor change about check_traces.sh and TCUtils.ps1 CheckCallTracesWithDelay, sometimes hot add memory will make VM occur call trace with "Out of memory", but it is not bug, here ignore oom call trace.
Test steps:
Test case 1: Verify VM does not crash when hot add memory by eatmemory (SMP).
Steps:
1. Setup VM as 4 virtual CPU, enable dynamic memory, and set up as below:
Startup memory - 4096 MB
Minimum memory - 1024 MB
Maximum memory - 4096 MB
2. Run # while true; do ./eatmemory 4G; done
(refer to https://github.com/julman99/eatmemory.git)
note: install steps:
#cd /tmp
#git clone …
> Add two new balloon cases for eatmemory stress

- WS2012R2/lisa/setupscripts/MMIO_Set_Invalid_GapSize.ps1
- WS2012R2/lisa/xml/retired_xml/MMIO_Tests.xml
Add one new test case MMIO_Set_Valid_GapSize, before already had MMIO_Set_InValid_GapSize, which was moved to retired xml.
Locally we have this MMIO_Set_Valid_GapSize manual case, so automate it based on MMIO_Set_InValid_GapSize.
Fix minor bug do - until to avoid endless loop.
Thank you.
> Add new test case for setting valid mmio value based on existing case
