LIS/lis-test

WS2012R2/lisa/remote-scripts/ica/perf_iperf.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2012R2/lisa/setupscripts/StartVM.ps1
WS2012R2/lisa/xml/NET_Tests.xml

- new setup script: StartVM.ps1 sets up additional Network Adapters for a second VM, starts it and configures the interface files in the OS before starting the main test VM.
- Private network related tests and Copy large file are now fully automated. The dependency VMs are now started and set up automatically.

Private network testing and Copy Large File test related changes.

---

WS2012R2/lisa/remote-scripts/ica/DM_VERIFY_LOADED.sh
WS2012R2/lisa/remote-scripts/ica/NET_CONFIGURE_NETWORK.sh
WS2012R2/lisa/remote-scripts/ica/NET_COPY_LARGE.sh
WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh
WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
WS2012R2/lisa/remote-scripts/ica/NET_OPERSTATE.sh
WS2012R2/lisa/remote-scripts/ica/NET_PROMISC.sh
WS2012R2/lisa/remote-scripts/ica/NET_STATIC_MAC.sh
WS2012R2/lisa/remote-scripts/ica/NET_TEST_NETWORK.sh
WS2012R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
WS2012R2/lisa/xml/DM_Tests.xml
WS2012R2/lisa/xml/NET_Tests.xml

- several bugfixes
- VLAN_TAGGING: now static IPs can be specified for the test interfaces (optional) and it actually works
- Jumbo frames and Change network type to internal tests are also fully automated: second VM is set up, started and configured by LISA. 
- All the networking tests are now fully automated

networking automation fixes and new features

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh
WS2012R2/lisa/xml/LTP.xml

This is the LISA - LTP integration. The current implementation works for RHEL 7, Ubuntu 14.04 and SLES 12

Added LTP testing

---

WS2012R2/lisa/remote-scripts/ica/NET_OPERSTATE.sh
WS2012R2/lisa/xml/NET_Tests.xml

Operstate fix

---

WS2012R2/lisa/remote-scripts/ica/Stress_Kernbench.sh
WS2012R2/lisa/setupscripts/Test50TimesReboot.ps1
WS2012R2/lisa/xml/StressTests.xml

- Added stress reboot script (it was missing in the git repo)
- Updated Kernbench test script
- Updated xml

Stress test updates

---

WS2012R2/lisa/xml/StorVHDx.xml
WS2012R2/lisa/xml/StorVhd.xml

Added test case to cover btrfs filesystem. Added cases to cover Hot Remove in SMP env.

TC Covered changes made to reflect ftm automation changes.

---

WS2012R2/lisa/remote-scripts/ica/STOR_VSS_Check_VSS_Daemon.sh
WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1

Adds a new remote script for distro-specific checking of the VSS daemon
state.

Fixes VSS tests for RHEL/CentOS 7

---

WS2008R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh
WS2008R2/lisa/setupscripts/NMI_2.4.2-AnalyseVmcore.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml
WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VSS_ISCSI_PartitionDisks.sh
WS2012R2/lisa/setupscripts/ChangeCPUIterated.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
WS2012R2/lisa/xml/CoreTests.xml

- VSS iSCSI
- VSS 3-chained
- refactored NTP timesync test according to latest discussions

Update to VSS scripts

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

Switched from `ntpstat 1`  to `service ntpd restart`

Check if "service ntp" is running

---

WS2012R2/lisa/setupscripts/AddHardDisk.ps1
WS2012R2/lisa/setupscripts/RemoveHardDisk.ps1

Removes external dependency for passthrough test case. Now for every test there's a vhd created which is being mounted and used as a passthrough.

Refactor for better passthrough support

---

WS2012R2/lisa/remote-scripts/ica/NET_CONFIGURE_NETWORK.sh
WS2012R2/lisa/remote-scripts/ica/NET_COPY_LARGE.sh
WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh
WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
WS2012R2/lisa/remote-scripts/ica/NET_PROMISC.sh
WS2012R2/lisa/remote-scripts/ica/NET_STATIC_MAC.sh
WS2012R2/lisa/remote-scripts/ica/NET_TEST_NETWORK.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/xml/NET_Tests.xml

- Interfaces are now set up using ifcfg files for all tests, eliminating errors for some distros with dhclient/dhcpcd
- Small improvement for external network tests

Refactored networking tests to increase compatibility

---

WS2008R2/lisa/stateEngine.ps1
WS2008R2/lisa/utilFunctions.ps1
WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/xml/NET_Tests.xml

NEW: RHEL 5 supported
UPDATE/FIX: Updated xml so tests can be run all at once

Update to Networking tests

---

WS2012R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
WS2012R2/lisa/remote-scripts/ica/FC_disks.sh
WS2012R2/lisa/remote-scripts/ica/FC_stressTest.sh
WS2012R2/lisa/remote-scripts/ica/Performance_IOzone.sh
WS2012R2/lisa/remote-scripts/ica/STOR_Big_Disk.sh
WS2012R2/lisa/remote-scripts/ica/STOR_Lis_Disk.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VSS_Disk_Fail.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VSS_ISCSI_PartitionDisks.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VSS_PartitionDisks.sh
WS2012R2/lisa/remote-scripts/ica/STOR_hot_remove.sh
WS2012R2/lisa/remote-scripts/ica/STOR_pass_offline.sh
WS2012R2/lisa/remote-scripts/ica/STOR_trim.sh
WS2012R2/lisa/remote-scripts/ica/Stress_IOzone.sh
WS2012R2/lisa/setupscripts/AddDisk.ps1
WS2012R2/lisa/setupscripts/AddHardDisk.ps1
WS2012R2/lisa/setupscripts/AddVhdxHardDisk.ps1
WS2012R2/lisa/stateEngine.ps1
WS2012R2/lisa/xml/FC_Tests.xml
WS2012R2/lisa/xml/StorVhd.xml

Changes to storage scripts dealing with /sys/devices/../sd* to support rhel5.x too. Added dependency auto install for FC stress test. Lowered lisa start up timeouts. Increased sleep between module reloads.

Automation improvements

---

WS2008R2/lisa/remote-scripts/ica/NET_CONFIGURE_NETWORK.sh
WS2008R2/lisa/remote-scripts/ica/NET_COPY_LARGE.sh
WS2008R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh
WS2008R2/lisa/remote-scripts/ica/NET_LEGACY.sh
WS2008R2/lisa/remote-scripts/ica/NET_OPERSTATE.sh
WS2008R2/lisa/remote-scripts/ica/NET_PROMISC.sh
WS2008R2/lisa/remote-scripts/ica/NET_STATIC_MAC.sh
WS2008R2/lisa/remote-scripts/ica/Utils.sh
WS2008R2/lisa/setupscripts/NET_ADD_NIC_MAC.ps1
WS2008R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2008R2/lisa/setupscripts/NET_REMOVE_NIC_MAC.ps1
WS2008R2/lisa/setupscripts/NET_SWITCH_NIC_MAC.ps1
WS2008R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml
WS2012R2/lisa/xml/NET_Tests.xml

Updated basic Networking tests for 2008R2. The following are working:
External
Internal
Operstate
Multiple NIC
Static MAC
Network Mode
Legacy Synthetic Network

Updated Networking tests on 2008R2

---

WS2008R2/lisa/remote-scripts/ica/CORE_LISmodules_version.sh
WS2008R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
WS2008R2/lisa/remote-scripts/ica/Core_Floppy_Disk.sh
WS2008R2/lisa/remote-scripts/ica/LIS_CD.sh
WS2008R2/lisa/setupscripts/CORE_RebootDiffMemory.ps1
WS2008R2/lisa/setupscripts/CORE_reload_modules.ps1
WS2008R2/lisa/setupscripts/ChangeCPUIterated.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml

CORE Tests now match the ones from WS2012R2.

CORE Tests modifications

---

WS2008R2/lisa/setupscripts/AddHardDisk.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml

Added option to specify disk size for AddHardDisk.ps1 on 2008R2

---

WS2008R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2008R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2008R2/lisa/setupscripts/StartVM.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml
WS2012R2/lisa/setupscripts/NET_BRIDGE.ps1
WS2012R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
WS2012R2/lisa/setupscripts/StartVM.ps1
WS2012R2/lisa/xml/NET_Tests.xml

New for 2008R2:
- guest only network
- vlan tagging
- copy large file
- jumbo frames
Fixed:
- xml improvements
- increased waiting time at VM booting

New 2008R2 Networking tests

---

WS2012R2/lisa/setupscripts/FCOPY_basic.ps1
WS2012R2/lisa/setupscripts/FCOPY_file_exists.ps1
WS2012R2/lisa/setupscripts/FCOPY_large_file.ps1
WS2012R2/lisa/setupscripts/FCOPY_overwrite.ps1
WS2012R2/lisa/setupscripts/INST_LIS_TestVMHeartbeat.ps1
WS2012R2/lisa/setupscripts/INST_LIS_TestVMShutdown.ps1
WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1

FCopy daemon check improvement and other code clean-up

Multiple fixes and code clean-up

---

WS2012R2/lisa/setupscripts/NET_ipinjection.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1
WS2012R2/lisa/xml/NET_Tests.xml

- IP injection script
- new function which generates an IP based on another one (this will be improved in the future). This function will be used in other testcases as well to minimize the manual intervention in NET_Tests.xml

IP injection automated

---

WS2012R2/lisa/setupscripts/Add-VHDXForResize.ps1
WS2012R2/lisa/xml/StorVHDx.xml

New features:
- possibility to specify disk type (dynamic, fixed)
- possibility to specify disk path (OPTIONAL)

LIS Big VHDX test case scenario changes

---

WS2012R2/lisa/xml/NET_Tests_ipv6.xml

XML for NetTest_ipv6

---

WS2012R2/lisa/setupscripts/NET_SendIPtoVM.ps1
WS2012R2/lisa/setupscripts/StartVM.ps1
WS2012R2/lisa/xml/NET_Tests.xml

- Reduced required parameters to run networking tests. 
- Relocated frequent parameters to the VM section
- Manually inserted Static IP addresses for Copy Large File and Jumbo frames are no longer required

Improved networking tests

---

WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
WS2012R2/lisa/xml/DM_Tests.xml

- optimized xml values
- optimized stressaptest parameters
- improved check of memory usage

Hot Add Remove improvements

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh
WS2012R2/lisa/xml/LTP.xml

Overall improvements and switched LTP to lite mode

Update LTP to run in lite mode

---

WS2012R2/lisa/setupscripts/VMBus_PanicNotifier.ps1

Also allowing more time for the VM state to change

Adding RHEL improvement

---

WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_server.sh
WS2012R2/lisa/xml/Perf_IPerf_IPv4_Panorama.xml

- RHEL: 
-disables firewall
- Ubuntu: 
-installs sysstat (sar)
ALL:
-runs iperf in ipv4 mode

Updated Iperf tests with distro specific setup

---

WS2012R2/lisa/remote-scripts/ica/STOR_Big_Disk.sh
WS2012R2/lisa/setupscripts/Add-VHDXForResize.ps1
WS2012R2/lisa/xml/StorVHDx.xml

To reduce the amount of real disk space usage of dynamic VHDX files, we
set the `-BlockSizeBytes` parameter to 1MB (from the default 32MB)

Large disk VHDX BlockSize improvement

---

WS2012R2/lisa/setupscripts/STOR_ExportImportVM.ps1

- Export-import now works on TH

ExportImport test support on TH

---

WS2008R2/lisa/remote-scripts/ica/buildKernel.sh
WS2012R2/lisa/remote-scripts/ica/buildKernel.sh

Added an function to detect operating system and also disabled Module Signature Verification.

Detect OS for buildkernel.

---

WS2012R2/lisa/setupscripts/DM_CleanShutdown.ps1
WS2012R2/lisa/setupscripts/DM_HighPriority.ps1
WS2012R2/lisa/setupscripts/DM_HotAdd.ps1
WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
WS2012R2/lisa/setupscripts/DM_MaxMemHonor.ps1
WS2012R2/lisa/setupscripts/DM_MinMemHonor.ps1
WS2012R2/lisa/setupscripts/DM_PressureChangesDemand.ps1
WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
WS2012R2/lisa/setupscripts/DM_SaveRestore.ps1
WS2012R2/lisa/setupscripts/DM_StartupLowCompete.ps1

All examples in DM test scripts are now correct.

Dynamic Memory: Changed .Example in Synopsis

---

WS2012R2/lisa/remote-scripts/ica/ltp_client.sh
WS2012R2/lisa/remote-scripts/ica/ltp_server.sh

Automation for RHEL LTP network tests.

LTP network tests for RHEL

---

WS2012R2/lisa/remote-scripts/ica/ltp_client.sh
WS2012R2/lisa/remote-scripts/ica/ltp_run.sh
WS2012R2/lisa/remote-scripts/ica/ltp_server.sh

Added LTP network tests for SLES

---

WS2012R2/lisa/setupscripts/DM_HotAdd_Stress_ng.ps1
WS2012R2/lisa/xml/DM_Tests.xml

1. Added stress-ng as a secondary testing option for DM HotAdd
2. Reduced timeout times in DM_Tests.xml

stressng addition for HotAdd 

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Also fixes comparison of memory sizes in CreateVMs

Add imageStoreDirectory support

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

1. Changed offset read from ntpdc to ntpq as ntpdc is deprecated.
2. Added SLES 11 support.
3. Fixed instalation command in SLES.

Updated CORE_TimeSync_NTP.sh

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

- Allow VHDs to be copied to remote hosts
- Fix static mac address setting
- Avoid conflict in differencing disk naming

Fix various issues with CreateVMs.ps1

---

WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_server.sh

- Now the test net interfaces are detected by the scripts (instead the assumed hardcoded eth1).
- Distro and kernel versions are included in the summary.
- Fixed compatibility issues with SLES 12.

IPERF: fixes and improvements

---

WS2012R2/lisa/remote-scripts/ica/perf_hadoopterasort.sh
WS2012R2/lisa/xml/perf_hadoopterasort.xml

1.Updated perf_hadoopterasort dependencies
2. Added hadoop version as parameter

Updated hadoop

---

WS2012R2/lisa/Infrastructure/Analyze-IperfResultsThroughputFromLinuxSar.ps1
WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
WS2012R2/lisa/xml/Perf_IPerf_IPv4_Panorama.xml

Also changed the way how dependency VM is shut down at IPERF tests.

Added ntttcp-for-linux Jenkins automated tests

---

WS2012R2/lisa/remote-scripts/ica/LIS_daemons.sh

Created a new function for compiling lis_daemons on Centos6.5

Update LIS_dameon.sh for Centos6.5

---

WS2012R2/lisa/xml/NET_LIVEMIG.xml

MultiCPU3_LiveMig testName was restored

Fixed NET_LIVEMIG.xml

---

WS2012R2/lisa/remote-scripts/ica/NET_Configure_Vxlan.sh
WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1
WS2012R2/lisa/xml/NET_Tests.xml

Created Vxlan network hang test.

Vxlan network tests

---

WS2012R2/lisa/xml/Perf_IPerf_IPv4_Panorama.xml

- Also added ntttcp to suitetests tag

Changing IPERF tool to latest version

---

WS2012R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2012R2/lisa/setupscripts/NET_SendIPtoVM.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
WS2012R2/lisa/setupscripts/Remove-VHDXHardDisk.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_Basic.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_BasicLM.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_DiskOver2TB.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowFS.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
WS2012R2/lisa/setupscripts/StartVM.ps1

- This fixes errors with all VHDX Resize tests running remotely
- Fixes some errors with VHDx tests
- Vlan Tagging and Trunking tests now can be run remotely

Improved support for running tests on remote servers

---

WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1

- VM memory can now be configured on a remote server

DM: Configure memory settings improvements

---

WS2008R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

Added NTP for sles on 2008R2 server

---

WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1

Fixed calling the correct script.

Fixed bash script call

---

WS2012R2/lisa/setupscripts/Test50TimesReboot.ps1

50 times reboot now handles VMs on remote servers.

Reboot stress test remote run fixed

---

WS2012R2/lisa/remote-scripts/ica/DM_HotAdd_Verify_udev.sh

Fixed script to match all distros.

Updated script with a better solution

---

WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh

The script is now setting a new MTU value only on the test NIC

Changes to NET_JUMBO_FRAMES.sh

---

WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_iperf_panorama_server.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
WS2012R2/lisa/remote-scripts/ica/ubuntu_proposed_kernel.sh
WS2012R2/lisa/xml/Ubuntu_kernel_proposed.xml

Automatically detects the Ubuntu release and installs the latest
available proposed kernel.

ubuntu proposed kernel automation

---

WS2012R2/lisa/remote-scripts/ica/NET_Copy_Different_MTU.sh

Script now changes MTU only on test NIC

NET_Copy_Different_MTU.sh fix

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1

1. if the hypervkvpd isn't started on VM  or the kvp doesn't work.  however, the parameter of ipv4 is specified in xml, the script should fail ,so add check the hypervkvpd whether it runs normally. 
2. make sure the whether  hypevkvpd  work normally or not, if it works normally,  the kvp on server side can get the value of OSName", "ProcessorArchitecture", "OSMajorVersion...of VM or failure

Add the function of checking kvp daemon

---

WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_GrowFSAfterResize.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_PartitionDisk.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_PartitionDiskAfterResize.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_PartitionDiskOver2TB.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_ReadWrite.sh
WS2012R2/lisa/setupscripts/STOR_VHDXResize_Basic.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_BasicLM.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_DiskOver2TB.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowFS.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
WS2012R2/lisa/xml/STOR_VHDXResize.xml

VHDXResize improvements

---

WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh
WS2012R2/lisa/setupscripts/NET_HotAddRemoveNIC.ps1
WS2012R2/lisa/xml/NET_Tests.xml

1. Split up NET_HotAddMultiNIC in 2 testcases: First one checks the NIC
Hot Add capability and second one checks for NIC Hot Remove capability.
2. Added RHEL and Ubuntu support for both testcases

Added NET_HotAddRemove testcase

---

WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh
WS2012R2/lisa/xml/NET_Tests.xml

Removed GetOSVersion function. It is now used from utils.sh

NET_VerifyHotAddMultiNIC.sh improvements

---

WS2012R2/lisa/remote-scripts/ica/KVP_VerifyHostInjectedItems.sh
WS2012R2/lisa/xml/KvpTests.xml

KVP_VerifyHostInjectedItems.sh will look for items in KVP pool 3.
Acceptance criteria
1.  The KVP pool 3 file has a size greater than zero.
2.  At least 8 (default value, can be changed in xml) items are present in pool 3.

Added KVP Verify Host Injected Items testcase

---

WS2012R2/lisa/remote-scripts/ica/KVP_VerifyHostInjectedItems.sh
WS2012R2/lisa/xml/KvpTests.xml

Changed default value of KVP items below the test will fail from 8 to 11

Changed default value for KVP Verify Host Injected Items

---

WS2012R2/lisa/remote-scripts/ica/FC_WWN.sh
WS2012R2/lisa/setupscripts/FC_WWN.ps1
WS2012R2/lisa/xml/FC_Tests.xml

Automation compares the WWN information between the host and guest

FC WWN automation

---

WS2012R2/lisa/setupscripts/VMBus_PanicNotifier_onKdump.ps1
WS2012R2/lisa/xml/VMBus_Tests.xml

Add case "Start kdump and trigger crash then verify there is event log on the host"

Add Verify get 18590 event when kdump is started testcases

---

WS2012R2/lisa/remote-scripts/ica/ubuntu_proposed_kernel.sh
WS2012R2/lisa/remote-scripts/ica/ubuntu_test_kernel.sh
WS2012R2/lisa/xml/Ubuntu_staging_kernels.xml

1. Renamed Ubuntu_kernel_proposed.xml to Ubuntu_staging_kernels.xml
2. XML creates 2 VMs instead of one
3. We can either choose to install a proposed kernel or a test kernel

Added new automation feature - Install test kernel

---

WS2012R2/lisa/remote-scripts/ica/ubuntu_proposed_kernel.sh
WS2012R2/lisa/remote-scripts/ica/ubuntu_test_kernel.sh

1. Code clean-up
2. Grub update for ubuntu_test_kernel.sh

Improvements to Ubuntu_staging_kernels

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1
WS2012R2/lisa/setupscripts/SQM_basic.ps1
WS2012R2/lisa/xml/KvpTests.xml

1. Added SQM_Basic testcase for WS2012, WS2012R2 and WS2016
2. Removed kvp daemon check from KVP_Basic because it is now checked on
SQM_Basic
3. Removed specific keys check for each WS. They are the same on all
versions

Added SQM_Basic testcase

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

fixed https://github.com/LIS/lis-test/issues/280

fix CreateVMs.ps1 for WS2012 (no R2)

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

If <isCluster> tag is set to "True" in xml, the vm will be created for
live migration operations.
The vm will be created on cluster storage, vhd will be copied there also
and finally the vm will be configured for High Availability

Added creating vm on cluster capability for CreateVMs.ps1

---

WS2012R2/lisa/remote-scripts/ica/STOR_Lis_Disk.sh
WS2012R2/lisa/xml/STOR_VHDX.xml

1.add filesystem ext4,xfs check every cases in  STOR_VHDX.xml and update STOR_Lis_Disk.sh to support filesystems parameter
2.Add check call trace function, sometime testing need to check if there is some call trace log to make sure the status is normal

Update STOR_Lis_Disk.sh and STOR_VHDX.xml

---

WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
WS2012R2/lisa/setupscripts/DM_CleanShutdown.ps1
WS2012R2/lisa/setupscripts/DM_HighPriority.ps1
WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
WS2012R2/lisa/setupscripts/DM_MaxMemHonor.ps1
WS2012R2/lisa/setupscripts/DM_MinMemHonor.ps1
WS2012R2/lisa/setupscripts/DM_RemoveUnderPressure.ps1
WS2012R2/lisa/setupscripts/DM_SaveRestore.ps1
WS2012R2/lisa/setupscripts/DM_StartupLowCompete.ps1
WS2012R2/lisa/setupscripts/ManualMem_Configure.ps1

1. Added remote run capability for all DM scripts
2. Manual Memory configure script now supports version 7 and higher vms.

DM remote run capability & Manual Mem configure script small fix

---

WS2012R2/lisa/setupscripts/Add-VHDXForResize.ps1

Added $vhdPath = $null. This adds remote run capability

Small fix for Add-VHDXForResize.ps1

---

WS2008R2/lisa/remote-scripts/ica/STOR_Large_Disk.sh
WS2008R2/lisa/setupscripts/INST_LIS_TimeSync.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml

fix stor_large_disk and timesync on 2008

fixes WS2008R2

---

WS2012R2/lisa/setupscripts/CORE_RebootDiffMemory.ps1

Verify the VM isn't only rebooted on host, but alos can be rebooted on guest with different ram

fix CORE_RebootDiffMemory to support reboot on guest

---

WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh

Solved a problem where script was failing if the newly added nic had other name than eth1

NET_VerifyHotAddMultiNIC.sh fix

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1
WS2012R2/lisa/setupscripts/KVP_DeleteKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_DeleteNonExistKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_ModifyNonExistKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_TestKvpGET.ps1
WS2012R2/lisa/setupscripts/KVP_VerifyGuestCreatedItem.ps1
WS2012R2/lisa/setupscripts/SQM_basic.ps1

1. Added remote run capability for KVP_Push_Key_Values
2. Added WS2016 support for KVP_DeleteNonExistKVPOnGuest and KVP_ModifyNonExistKVPOnGuest
3. Code formatting & cleanup

Various fixes for KVP test suite

---

WS2012R2/lisa/setupscripts/NET_ipinjection.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

NET_ipinjection now tries to inject up to 3 IPs. After 3 unsuccessful attempts, test fails

Fix for NET_ipinjection.ps1

---

WS2012R2/lisa/setupscripts/INST_LIS_TestVMHeartbeat.ps1

Add scenario of uncheck and check integrate service of heartbeat, verify the status of Heartbeat  is normal on Hyper-V manager.

fix VMHeartbeat

---

WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_ReadWrite.sh
WS2012R2/lisa/xml/STOR_VHDX.xml
WS2012R2/lisa/xml/STOR_VHDXResize.xml

1.Update STOR_VHDX.xml by replacing Dynamic to Fixed to avoid confuse
2.Add xfs file system for STOR_VHDXResize.xml
3.Update STOR_VHDXResize_ReadWrite.sh to support call trace warnging log

Update STOR_VHDX xml and support call trace log output for resize

---

WS2008R2/lisa/remote-scripts/ica/KVP_VerifyKeyValue.sh
WS2008R2/lisa/setupscripts/KVP_VerifyGuestCreatedItem.ps1
WS2008R2/lisa/xml/FTM_win2008r2.xml
WS2012R2/lisa/remote-scripts/ica/KVP_VerifyHostInjectedItems.sh
WS2012R2/lisa/remote-scripts/ica/KVP_VerifyKeyValue.sh
WS2012R2/lisa/setupscripts/KVP_VerifyGuestCreatedItem.ps1
WS2012R2/lisa/xml/KvpTests.xml

Changes made to both WS2012R2 & WS2008R2 scripts.

KVP: Added OS architecture detection

---

WS2012R2/lisa/xml/DM_Tests.xml

Update DM xml to push the file and check for Call Traces.

Update DM xml

---

WS2012R2/lisa/remote-scripts/ica/performance_ab_client.sh
WS2012R2/lisa/remote-scripts/ica/performance_ab_server.sh
WS2012R2/lisa/xml/Perf_AB.xml

Apache benchmark automation

---

WS2012R2/lisa/remote-scripts/ica/provisionLinuxForLisa.sh

1. Fiexed varibale name issue; 
2. Added RHEL6 support.

Add the rhel6 support of provisionVM

---

WS2012R2/lisa/remote-scripts/ica/check_clocksource.sh
WS2012R2/lisa/xml/CoreTests.xml

Check the clocksource inside VM

Add a case of clocksource in VM

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

Added 1 second sleep. This solves high CPU usage

Fixed NTP TimeSync

---

WS2012R2/lisa/remote-scripts/ica/pxe_install.sh
WS2012R2/lisa/setupscripts/pxe_install.ps1
WS2012R2/lisa/xml/PXE_gen1.xml

This test suite needs a PXE Server with tftp, dhcp and http server
already set up and running.
This test suite will use the given PXE server to set up a new install of
Ubuntu, RHEL or SLES.
Test list:
PXE_basic - basic check, no install
PXE_install_singleCpu - will install on a vm with single vcpu
PXE_install_SMP - will install on a vm with multiple vcpus
All checks are made by verifying the heartbeat and sqm data

Added PXE install Test Suite (Gen 1)

---

WS2012R2/lisa/remote-scripts/ica/BuildKernelWithPatches.sh

CONFIG_PCI_HYPERV is required for PCI passthrough and related features.

Enable CONFIG_PCI_HYPERV module

---

WS2012R2/lisa/remote-scripts/ica/NUMA_check.sh
WS2012R2/lisa/remote-scripts/ica/NUMA_off_kernel.sh
WS2012R2/lisa/setupscripts/NUMA_Off_Kernel.ps1
WS2012R2/lisa/xml/CoreTests.xml

"'numa=off' was added as kernel boot params.

Added a new case, which verifies whether the NUMA is turned off 

---

WS2012R2/lisa/remote-scripts/ica/Core_LIS_CD.sh

fix for ubuntu

---

WS2012R2/lisa/remote-scripts/ica/NUMA_check.sh
WS2012R2/lisa/remote-scripts/ica/NUMA_off_kernel.sh

Disable_NUMA_By_Kernel test is working for Sles, Ubuntu, CentOS, Rhel.

Update Disable_NUMA_By_Kernel test

---

WS2012R2/lisa/remote-scripts/ica/STOR_Lis_Disk.sh

Added "-f" option when file system is created.

Update make file system xfs.

---

WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/setupscripts/CORE_RebootDiffMemory.ps1

fixed CORE_RebootDiffMemory test and is_rhel7 function in utils to support 7.x rhel versions

fixed CORE_RebootDiffMemory

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1
WS2012R2/lisa/xml/KvpTests.xml

Set "DE_changed=yes" Disable and Enable Key-Value Pair Exchange service and Verify the basic KVP read operations work that just be supported  on more than RHEL7.3 .Here is a bug1074407 on less RHEL7.2 .

add DE_changed=yes to support related with operation integrated service

---

WS2012R2/lisa/setupscripts/ManualMem_Configure.ps1

Script will support now VM version 7 or greater

ManualMem fix

---

WS2012R2/lisa/Infrastructure/PXE/autoinstGen1.xml
WS2012R2/lisa/Infrastructure/PXE/autoinstGen2.xml
WS2012R2/lisa/remote-scripts/ica/pxe_install.sh

1. Typo fix in pxe_install.sh
2. Improvements in default AutoYAST files found in Infrastructure/PXE folder

PXE improvements

---

WS2012R2/lisa/remote-scripts/ica/NET_ETHTOOLS.sh
WS2012R2/lisa/xml/NET_Tests.xml

Add case to check tcp-segmentation-offload scatter-gather rx-checksumming and tx-checksumming of Synthetic Network Adapter are set on

Add case of checking some keys with ethtool

---

WS2012R2/lisa/remote-scripts/ica/NET_set_static_ip.sh
WS2012R2/lisa/remote-scripts/ica/performance_redis.sh
WS2012R2/lisa/xml/Perf_Redis.xml

added perf redis

---

WS2012R2/lisa/setupscripts/Add-VHDXForResize.ps1

Now we can add a vhd to the IDE Controller

Fix add to ide

---

WS2012R2/lisa/remote-scripts/ica/ubuntu_proposed_kernel.sh

Remove character in addition

---

WS2012R2/lisa/remote-scripts/ica/NUMA_off_kernel.sh
WS2012R2/lisa/setupscripts/NUMA_Off_Kernel.ps1

Re-write NUMA_off_kernel.sh by sourcing utils.sh, fix sed command error.
Resolve format error and LogMsg param error.

Numaoffkernel

---

WS2012R2/lisa/remote-scripts/ica/STOR_NFS_Client.sh
WS2012R2/lisa/xml/STOR_VHDX.xml

Add a case to verify nfs storage

Storage nfs

---

WS2012R2/lisa/Infrastructure/Analyze-FIOResults.ps1

updated parser to collect latency for each read/write

fio results parser: added latency

---

WS2012R2/lisa/lisa.ps1
WS2012R2/lisa/utilFunctions.ps1

Added one more argument to SendEmail and SummaryToString methods in order to create the proper path to the log folder.

Fix hard coded log folder path

---

WS2012R2/lisa/remote-scripts/ica/NET_ETHTOOLS.sh

Removed distro verification and added some exit codes in case of fail.

Fixed ethtool script

---

WS2012R2/lisa/setupscripts/NET_ipinjection.ps1

The test now checks if hv_set_ifconfig is in the VM before continuing to try the injection.

IP INJECTION: added hv_set_ifconfig check

---

WS2012R2/lisa/setupscripts/INST_LIS_TimeSync.ps1
WS2012R2/lisa/setupscripts/INST_LIS_TimeSyncServiceDisableEnable.ps1
WS2012R2/lisa/setupscripts/INST_timesync_pausedVM.ps1
WS2012R2/lisa/setupscripts/INST_timesync_savedVM.ps1

Met errors below when cases are ran on different server:
Windows time: 1/8/2016 8:16:14
Unix time:  8/1/2016 8:16:14
so need to get Unix time with windows system time format

convert time of VM with windows system time format

---

WS2012R2/lisa/setupscripts/NET_filecopy_scp.ps1

Changing reported times to minutes for filecopy_scp and other code fixes

Changing reported time to minutes for filecopy_scp

---

WS2012R2/lisa/Infrastructure/lisa-parser/README.md
WS2012R2/lisa/Infrastructure/lisa-parser/file_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/sql_utils.py

- Added quotation marks for table_name in sql_utils for cases where table names contain special characters
- Modified the xml parser so it can skip field that are empty
- Updated README

Parser improvements

---

WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
WS2012R2/lisa/remote-scripts/perf_utils.sh

Adding performance prep script to customize sysctl and i/o disk scheduler

---

WS2012R2/lisa/setupscripts/DM_HotAdd.ps1
WS2012R2/lisa/setupscripts/DM_HotAddRemove.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

Hot Add tests are now checking for kernel version. If this is 2.x, we apply considerably lower pressure on the memory. Tested with kernels 2.x, 3.x and 4.x

DM Hot Add with Stressapptest improvements and fine tuning

---

WS2012R2/lisa/xml/STOR_VHDX.xml

Updated TC_COVERED IDs and sorted test cases

STOR VHDx XML changes and TC_COVERED updates

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

CreateVMs.ps1 minor fix

---

WS2012R2/lisa/Infrastructure/lisa-parser/file_parser.py

Tested final NTTTCP perf test version on a Jenkins run

Enhance perf run zip logs handling

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

On some hosts the cmdlet is not present and PS throws an error

Added check for Get-ClusterResource cmdlet

---

WS2012R2/lisa/Infrastructure/lisa-parser/file_parser.py

Add lisa parser support for perf tests with multiple zipped log instances

---

WS2012R2/lisa/Infrastructure/lisa-parser/file_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/test_run.py

Change FIO logs matching pattern and adjust column names

---

WS2012R2/lisa/setupscripts/AddVhdxHardDisk.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthCleanup.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthSetup.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthTestCase.ps1
WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1
WS2012R2/lisa/setupscripts/NUMA_Off_Kernel.ps1
WS2012R2/lisa/setupscripts/RemoveIsoFromDvd.ps1
WS2012R2/lisa/setupscripts/RemoveVhdxHardDisk.ps1

fix bug of get error controllerID

---

WS2012R2/lisa/Infrastructure/lisa-parser/test_run.py

Add NTTTCP and FIO log data sorting by IPversion, connections and QDepth

---

WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_PartitionDisk.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_PartitionDiskOver2TB.sh
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1
WS2012R2/lisa/xml/STOR_VHDXResize.xml

Add five test cases about groving/shrink IDE/SCSI disk both over 2T and smaller size

Add cases about storage resizeshrink

---

WS2012R2/lisa/Infrastructure/lisa-parser/config.py
WS2012R2/lisa/Infrastructure/lisa-parser/config/demo_regexes.csv
WS2012R2/lisa/Infrastructure/lisa-parser/config/demo_tests.csv
WS2012R2/lisa/Infrastructure/lisa-parser/parse_build.py

This PR contains the database parser for Long Term testing and the examples for the config files needed.

added parser for long_term

---

WS2012R2/lisa/remote-scripts/ica/NET_TEST_NETWORK.sh
WS2012R2/lisa/setupscripts/InjectIPconstants.ps1
WS2012R2/lisa/setupscripts/NET_UTILS.ps1
WS2012R2/lisa/xml/NET_Tests.xml
WS2012R2/lisa/xml/NET_Tests_IPv6.xml

Added a new script which is generating PING_SUCC, PING_FAIL, PING_FAIL, STATIC_IP and NETMASK parameters according to the running test

refactoring net tests

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_DisableVF.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_basic.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multiple_fileCopy.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_VerifyVF_basic.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_compareRTT.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/setupscripts/NET_UTILS.ps1
WS2012R2/lisa/setupscripts/SR-IOV_Replication.ps1
WS2012R2/lisa/setupscripts/SR-IOV_SavePauseVM.ps1
WS2012R2/lisa/setupscripts/SR-IOV_enable.ps1
WS2012R2/lisa/xml/SR-IOV.xml

(1)Added new test suite, SR-IOV. [More test will be added]
Test Cases list (not final list):
Verify VF showing up in VM with lspci command.
Test the bonding scripts, verify and update the NIC config files as
needed.
Verify VF can send/receive packets
Run ping tests and confirm RTT is reduced from synthetic NIC cases
Disable VF, verify SR-IOV Failover is working
Ping using VM with multiple NICs bound to SR-IOV
File copy using VM with multiple NICs bound to SR-IOV
Pause a VM with single NIC SR-IOV
Pause a VM with multiple NICs bound to SR-IOV
Save a VM with single NIC SR-IOV
Save a VM with multiple NICs bound to SR-IOV
Using two Hyper-V hosts with replication enabled, failover a VM with
SR-IOV to host that supports SR-IOV
Using two Hyper-V hosts with replication enabled, failover a VM with …

New Test Suite: SR-IOV

---

WS2012R2/lisa/setupscripts/NET_UTILS.ps1
WS2012R2/lisa/setupscripts/SR-IOV_LiveMigration.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MultipleLinuxVMs.ps1
WS2012R2/lisa/setupscripts/SR-IOV_iPerf.ps1
WS2012R2/lisa/xml/SR-IOV.xml
WS2012R2/lisa/xml/SR-IOV_LM.xml

Added migration, iperf and multiple linux VMs tests

SR-IOV automation: 2nd sprint

---

WS2012R2/lisa/Infrastructure/Aio.sh

added environment setup script for VMs

added AIO.sh

---

WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/lisa_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/sql_utils.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/virtual_machine.py
WS2012R2/lisa/remote-scripts/ica/NET_MAX_NIC.sh

LISA Parser will check the data from the database to ensure correct insertion. Also a revert method was added before starting the VM, in order to prevent situations in which the VM won't boot.
Max NIC - In some cases extra interfaces are present on the VM. A fix was added to remove them from the array that contains the interfaces that should be configured.

Parser improvement + Max NIC fix

---

WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd_reboot.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_MultipleAddRemove.ps1
WS2012R2/lisa/xml/Runtime_Memory_Resize_Tests.xml

Made some adjustments to memory values and time sleeps to avoid
false-positive results

Runtime Memory HotAdd adjustments

---

WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh

- fixed legacy and synthetic interface checks, this should eliminate some isolated issues
- removed unnecessary code in legacy adapter test

NET: Fixed interface checks

---

WS2012R2/lisa/lisa.ps1
WS2012R2/lisa/setupscripts/CreateVMs.ps1

add lisa global parameter <VhdDir> representing the directory in which the VHD file will be copied when CreateVMs script is used

add VhdDir global parameter

---

WS2012R2/lisa/setupscripts/NET_ADD_NIC_MAC.ps1
WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1
WS2012R2/lisa/setupscripts/NET_PRIVATE_NETWORK.ps1
WS2012R2/lisa/setupscripts/NET_REMOVE_NIC_MAC.ps1
WS2012R2/lisa/setupscripts/NET_SWITCH_NIC_MAC.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1
WS2012R2/lisa/xml/NET_Tests.xml

1. Added random generated MAC in NET_TESTS
2. VLAN Tagging testing changed from External to Private

NET_TESTS improvements

---

WS2012R2/lisa/setupscripts/StartVM.ps1

StartVM.ps1 was not included in the previous NET_TESTS changed, which
broke some net tests.

[FIX] Changed StartVM.ps1 to accomodate changes in NET_TESTS.xml

---

WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1
WS2012R2/lisa/xml/STOR_VSS_Backup_Tests.xml

1. Remove remote-script function that has been included in TCUtils.ps1
2. Adjust the time of backuping VM to wait for the operation finish completely , it is not enough for RHEL6
3. Change ISO path

update Backup Cases

---

WS2012R2/lisa/remote-scripts/ica/PartitionDisks.sh
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1

show PartitionDisk.sh logs in lisa summary

improvements for VSS automation

---

WS2012R2/lisa/remote-scripts/ica/Core_LIS_CD.sh
WS2012R2/lisa/setupscripts/StartVM.ps1
WS2012R2/lisa/stateEngine.ps1

Here are some scenario need to be checked
1. make sure which cd drive mounted an ISO
2. Adjust time to wait for VM started completely
3. Sometimes, The VM will disappear if the restore failed when do the cases related to backup&restore cases, so need to check if VM exist in shutting VM

add some checking point

---

WS2012R2/lisa/tools/aws/connector.py
WS2012R2/lisa/tools/aws/tests/run_terasort.sh

Added terasort test for a multi-node hadoop cluster (tested Hadoop 2.7.3 on Ubuntu 16.04 using 4 nodes cluster for 500000000 teragen records)

Adding terasort test

---

WS2012R2/lisa/remote-scripts/ica/NET_Corruption.sh
WS2012R2/lisa/setupscripts/NET_Corruption.ps1
WS2012R2/lisa/xml/NET_Tests.xml

The following automation transfers a file from a linux VM
to a WS host using netcat. It checks for call traces,
during the transfer process, and also compares the
file hashes in order to validate the transfer result.

Add new test case for net corruption bug

---

WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
WS2012R2/lisa/xml/NET_Tests.xml

add NET_Multicast test case

---

WS2012R2/lisa/remote-scripts/ica/NET_Copy_Both_Ways.sh
WS2012R2/lisa/xml/NET_Tests.xml

New test case atempts to copy two large files (~10GB),
one from VM1 to VM2 and the other from VM2 to VM1, at the
same time.
Test script creates the two files, from /dev/urandom, starts
the two scp processes at the same time, and compares the md5sums
of the two files at the end.

Added test case that starts two copy processes

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Delete all VMs which contain test VM name from cluster group

add cluster VM cleanup before creation

---

WS2012R2/lisa/Infrastructure/aio.sh

Moved the working directory where the binaries were downloaded to tmp
and added a cleanup function to delete the files if the installation was
successfully.

Moved working directory and added cleanup function

---

WS2012R2/lisa/remote-scripts/ica/NET_Corruption.sh

Renamed InstallNC function to InstallNetcat.
Removed duplication of iptables flush.
Changed corruption command in order to affect eth1.

Refactored script

---

WS2012R2/lisa/remote-scripts/ica/LIS_daemons.sh

Overall code cleanup.
Standardized messages across functions.
Improved SLES LIS dependency files installation.

Fixes for the upstream LIS daemons installation

---

WS2012R2/lisa/Infrastructure/aio.sh
WS2012R2/lisa/remote-scripts/ica/Sysbench.sh

Updated Autoconf to latest version to fix Sysbench installation
problem and added sysbench prepare and cleanup commands. Updated
aio.sh to install the necessary packeges on Ubuntu.

Fixed Sysbench failure on RHEL and Ubuntu

---

WS2012R2/lisa/remote-scripts/ica/STOR_Verify_Sector_Size.sh

Used Parted to create partition instead of fdisk in order to force
the start sector to be 2048 instead of 63.

Fixed Verify_SectorSize failure

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh

Until now, the automation checked only for the Intel drivers. Now it
checks both Intel and Mellanox

SR-IOV: Added Mellanox driver compatibility

---

WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/file_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/test_run.py

This is part of the request to collect more data from NTTTCP performance test, and is valid only with the coresponding changes to the automation script

Add parser support for NTTTCP perf cycles/byte and fix latency conversion

---

WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_server.sh
WS2012R2/lisa/remote-scripts/ica/perf_utils.sh

- adding  Cycle/bytes on the receiver side
- adding new functions in perf_utils.sh

Adding Cycle/bytes on the receiver side.

---

WS2012R2/lisa/remote-scripts/ica/Sysbench.sh

Fixed Sysbench warning due to deprecated syntax and changed the
passing criterion for CPU and FileIO tests.

Fixed Sysbench warnings

---

WS2012R2/lisa/setupscripts/NET_VLAN_TAGGING.ps1
WS2012R2/lisa/setupscripts/NET_VLAN_TRUNKING.ps1

VLAN tagging and VLAN trunking tests are now reporting the test covered
ID.

VLAN tests fixes

---

WS2008R2/lisa/remote-scripts/ica/KVP_VerifyHostInjectedItems.sh
WS2008R2/lisa/xml/FTM_win2008r2.xml

Added KVP_HostInjectedItems to Widows Server 2008r2 tests suites

Added KVP HostInjectedItems test to WS2008r2

---

WS2012R2/lisa/remote-scripts/ica/Install_LIS.sh
WS2012R2/lisa/setupscripts/Deploy_scenarios.ps1
WS2012R2/lisa/xml/LIS_Scenarios.xml

1. XML file was refreshed to be more user-friendly
2. More logging was added (TC covered, LIS version installed, etc)
3. Various improvements

LIS_Deploy improvements

---

WS2012R2/lisa/setupscripts/Add-VHDXHardDiskWithLocation.ps1
WS2012R2/lisa/setupscripts/AddDisk.ps1
WS2012R2/lisa/setupscripts/AddFloppyDisk.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthCleanup.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthSetup.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthTestCase.ps1
WS2012R2/lisa/setupscripts/INST_LIS_ShutdownServiceDisableEnable.ps1
WS2012R2/lisa/setupscripts/InsertIsoInDvd.ps1

Function GetRemoteFileInfo is present in the TCUtils.ps1, so we source it and remove duplicate code

Code cleanup for function GetRemoteFileInfo

---

WS2012R2/lisa/setupscripts/AddHardDisk.ps1

This power shell script can be used to add a single or multiple physical disks to a VM.

Added new description for RAID configuration

---

WS2012R2/lisa/remote-scripts/ica/PC_Stop_VSS_Daemon.sh
WS2012R2/lisa/setupscripts/Production_checkpoint_failback.ps1

This TC gave a lot of false positive results because it was not looking
properly for the VSS service name

Fixed Production Checkpoint Failback TC

---

WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1
WS2012R2/lisa/xml/STOR_VSS_Backup_Tests.xml

Consolidating functions and overall code cleanup.

VSS tests code cleanup

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1
WS2012R2/lisa/setupscripts/KVP_DeleteKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_DeleteNonExistKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_ModifyNonExistKeyValue.ps1
WS2012R2/lisa/setupscripts/KVP_TestKvpGET.ps1
WS2012R2/lisa/setupscripts/KVP_VerifyGuestCreatedItem.ps1
WS2012R2/lisa/setupscripts/SQM_basic.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1
WS2012R2/lisa/setupscripts/pxe_install.ps1
WS2012R2/lisa/xml/KvpTests.xml

Moved function KvpToDict to TCUtils.ps1 and other small code fixes

KVP tests code consolidation

---

WS2012R2/lisa/OSAbstractions.ps1
WS2012R2/lisa/stateEngine.ps1
WS2012R2/lisa/utilFunctions.ps1

Revert "Migrate xiaofeng's ESX-lisa commit to create xml report by updating O…"

---

WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_3Chain_VHD.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MaxVMs.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MoveVHD.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

Moved GetParentVHD and CreateChildVHD function to TCUtils in order
to reduce redundancy.

Moved GetParentVHD and CreateChildVHD to TCUtils

---

WS2012R2/lisa/setupscripts/STOR_VSS_3Chain_VHD_backup.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_DiskStress.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Fail.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISCSI.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_ISO_NoNetwork.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_Partition.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1
WS2012R2/lisa/setupscripts/STOR_VSS_Utils.ps1

Common code blocks from VSS test scripts were
moved to separate, single purpose functions in
the STOR_VSS_Utils.ps1 script.

Refactored VSS powershell scripts

---

WS2012R2/lisa/setupscripts/SR-IOV_ChangeRSS.ps1
WS2012R2/lisa/setupscripts/SR-IOV_iPerf.ps1

Minor fixes to SR-IOV automation

SR-IOV minor changes

---

WS2012R2/lisa/remote-scripts/ica/Performance_FIO.sh
WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
WS2012R2/lisa/xml/Perf_FIO.xml

- Updated perf_utils.sh with a few functions  regarding download and configure FIO tool;
- Added in perf_utils.sh new function for run FIO with single disk and multiple disks in raid0

Performance_FIO.sh code factored

---

WS2012R2/lisa/remote-scripts/ica/perf_utils.sh

Added GetDistro function in perf_utils.sh to able to install file system on CentOS 6.x

Added GetDistro in perf_utils.sh

---

WS2012R2/lisa/remote-scripts/ica/STOR_VHDXResize_ReadWrite.sh

Refactored the STOR_VHDXResize_ReadWrite.sh script
by removing duplicated code.
Added extra steps that involve file creation and
checksum check.

Extended checks for ReadWrite script

---

WS2012R2/lisa/setupscripts/RemoveVhdxHardDisk.ps1

Added minor changes to fix remote capabilities for Stor_VHDX tests on Nano Server

Fixed remote capability for Stor_VHDX tests on Nano Server

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
WS2012R2/lisa/setupscripts/ChangeCPU.ps1
WS2012R2/lisa/setupscripts/SR-IOV_Deattach_NIC.ps1
WS2012R2/lisa/setupscripts/SR-IOV_Host_Disable.ps1
WS2012R2/lisa/setupscripts/SR-IOV_Stress_SavePause.ps1
WS2012R2/lisa/setupscripts/SR-IOV_enable.ps1
WS2012R2/lisa/xml/SR-IOV.xml
WS2012R2/lisa/xml/SR-IOV_LM.xml

>>5 new Test Cases were added:
- Max vCPU test
- Disable/Enable SR-IOV from physical NIC
- Change between vSwitches with/without SR-IOV
- Pause VM Stress test  (Replacing 'Pause VM with Multiple SR-IOV NICs')
- Save VM Stress test (Replacing 'Save VM with Multiple SR-IOV NICs')
>>Added 'max' parameter to ChangeCPU.ps1 - this is needed by SR-IOV 'Max vCPU' TC
>>Changed the TC codes to accommodate the new TCs
>> Minor improvements to existing SR-IOV code

SR-IOV: Added 5 new TCs

---

WS2012R2/lisa/remote-scripts/ica/NET_VerifyBootNoNIC.sh
WS2012R2/lisa/setupscripts/NET_BootNoNICHotAddNIC.ps1

A new set of config steps were added so
that the automation can run on rhel/centos
and ubuntu distros.
For rhel/centos the same method of using
the rc.local file, to run a script on startup,
was used. For ubuntu the script is triggered
by a cron job on reboot (rc.local config
was not properly working on some versions)
Also redundant code was removed from the
bash script.

Added extra config to cover other distros

---

WS2012R2/lisa/setupscripts/ChangeCPU.ps1
WS2012R2/lisa/xml/SR-IOV.xml

Also defined the maximum numbers of cores for the SR-IOV max vCPUs test
in order to match the NUMA topology

code cleanup and function consolidation

---

WS2012R2/lisa/setupscripts/RemoveFloppyDisk.ps1
WS2012R2/lisa/setupscripts/STOR_TakeRevert_Snapshot.ps1
WS2012R2/lisa/xml/STOR_VHD.xml

consolidated function RunRemoteScript and also checking for the new VM
IP as that can change during the reboot operation.
Added missing dependency bash script check_traces

code changes for STOR_TakeRevert_Snapshot.ps1

---

WS2012R2/lisa/remote-scripts/ica/NET_JUMBO_FRAMES.sh

- Changed the max MTU tested to 61440
- Changed the max ping packet size to 61404
- Improved logging

Improvements to NET_JUMBO_FRAMES.sh

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_DisableVF.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_ModuleReload.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
WS2012R2/lisa/setupscripts/SR-IOV_DisableNIC.ps1
WS2012R2/lisa/xml/SR-IOV.xml
WS2012R2/lisa/xml/SR-IOV_LM.xml

1. Added two new TC: ModuleReload and DisableNIC
2. Improved existing DisableVF TC - added ifup VF after ifdown VF
3. Changed the TC codes: all failover test have been grouped
4. Removed deprecated dependencies from SR-IOV_Utils.sh

SR-IOV: 2 Test Cases added

---

WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
WS2012R2/lisa/xml/NET_Tests.xml
WS2012R2/lisa/xml/SR-IOV.xml

Modified NET_Multicast.sh and SR-IOV_Multicast.sh to use ping instead of omping for multicast testing.

Switched to ping for multicast testing

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh

Fix SR-IOV_Multicast.sh typos

---

WS2012R2/lisa/setupscripts/DiffDiskGrowthSetup.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

Also minor update TCUtils.ps1 for variable definition for "$Passed" by adding "-Force".

Update DiffDiskGrowthSetup.ps1 to remove DVD if there is DVD

---

WS2012R2/lisa/setupscripts/STRESS_mtu_netvsc_reload.ps1
WS2012R2/lisa/xml/StressTests.xml

This test script will change MTU for 5 times and reload netvsc for 25
times. If after those changes VM is still responsive, test is passed.

Stress TC added: Change MTU & Reload Netvsc

---

WS2012R2/lisa/setupscripts/RemoveVhdxHardDisk.ps1

Changed condition for RemoveVHDXDiskDrive to throw an error when
trying to remove Lun 0 on Controller 0

Fixed RemoveVHDXDiskDrive

---

WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1
WS2012R2/lisa/xml/FCOPY_Tests.xml

Added a new test which disables and enables Guest Services a number
of times and then attempts to copy a 5GB file from host to guest using
the Copy-VMFile cmdlet.

Added FCopy test case

---

WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1

Improved the way in which the script detects the FCopy daemon

Improved hv_daemon name detection

---

WS2012R2/lisa/setupscripts/NMI_different_vmStates.ps1

Skip NMI_different_vmState test for 2012 host

---

WS2012R2/lisa/setupscripts/FCOPY_basic.ps1
WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1
WS2012R2/lisa/setupscripts/FCOPY_file_exists.ps1
WS2012R2/lisa/setupscripts/FCOPY_large_file.ps1
WS2012R2/lisa/setupscripts/FCOPY_non_ascii.ps1
WS2012R2/lisa/setupscripts/FCOPY_overwrite.ps1
WS2012R2/lisa/setupscripts/fcopy_repeated_delete.ps1

Skip fcopy test for 2012 host, even has dependency host version defined in Fcopy_Tests.xml, locally we maintain one xml for all the cases, suggest to update upstream script slightly. 

Skip fcopy test for 2012 host

---

WS2012R2/lisa/setupscripts/ChangeCPUIterated.ps1

Added a check of VM OS architecture and in case of 32 bit OS the
maximum CPU count is limited to 32.

Fixed Multi_CPU_Test in case of 32bit guest OS

---

WS2012R2/lisa/remote-scripts/ica/kexec_git_install.sh

This installs kexec from git and it's used in Upstream testing

Added kexec install script

---

WS2012R2/lisa/xml/NET_Tests_IPv6.xml

- Removed MAC addresses from NET_Tests_IPv6
- Removed unused TCs

NET_Tests_IPv6 refactoring

---

WS2008R2/lisa/remote-scripts/ica/Utils.sh
WS2008R2/lisa/xml/FTM_win2008r2.xml

Small improvements to fix network tests on Windows Server 2008R2

Fix for Network tests on WS2008R2

---

WS2012R2/lisa/setupscripts/AddHardDisk.ps1

Fixed Remove-VMDvdDrive errors caused by an attempt to remove
the DvD drive from IDE controller while VM was running.

Fixed Remove-VMDvdDrive errors while running SCSI tests

---

WS2012R2/lisa/remote-scripts/ica/NET_TEST_NETWORK.sh

Fixed multipleNIC failures on IPv6 tests

Fixed multipleNIC fail on IPv6 tests

---

WS2012R2/lisa/setupscripts/Add-VHDXHardDiskWithLocation.ps1
WS2012R2/lisa/setupscripts/AddHardDisk.ps1
WS2012R2/lisa/setupscripts/AddVhdxHardDisk.ps1
WS2012R2/lisa/setupscripts/DiffDiskGrowthSetup.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

Moved CreateController function from multiple setupscripts to TCUtils.ps1

Storage tests consolidation

---

WS2012R2/lisa/remote-scripts/ica/vmbus_verify_interrupts.sh

Add skip condition if hyperv interrupts are not being logged.

vmbus interrupts - skip if no records of hyperv

---

WS2012R2/lisa/stateEngine.ps1

In some cases hv_vmbus is not present in the Guest VM. Added a check for
netvsc too

Improved LIS version lookup in stateEngine.ps1

---

WS2012R2/lisa/xml/STOR_VHDX.xml

Updated link for VHDx_SCSI_Dynamic_Wget_File test

Updated Wget link

---

WS2012R2/lisa/Infrastructure/lisa-parser/README.md
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/config.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/lisa_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/monitor.py

Two new options were added so that the parser can provide list of issues after a test run in a json format (-R report_file_path) and a summary of previous reports, in a csv file, so it aid analyzing those specific issues (-S reports_folder_path).

Added reporting option to lisa parser

---

WS2012R2/lisa/xml/NET_LIVEMIG.xml

Increase the values for the vCPUs and VM Memory ammounts

Live Migration tests changes

---

WS2012R2/lisa/setupscripts/STOR_VSS_BackupRestore_State.ps1

Change Action to ErrorAction, fix minor error.

Minor fix error about STOR_VSS_Backup Saved Status for ErrorAction

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh

define regular stable releases in order to avoid unstable builds

update LTP to use stable releases

---

WS2012R2/lisa/setupscripts/NET_BootNoNICHotAddNIC.ps1
WS2012R2/lisa/setupscripts/NET_HotAddMultiNIC.ps1
WS2012R2/lisa/setupscripts/NET_HotAddRemoveNIC.ps1
WS2012R2/lisa/setupscripts/NET_HotAddRemove_Max_NIC.ps1

Added skipped state for Hot Add/Remove tests for Gen2 VMs

Added Skipped state to Hot Add/Remove tests

---

WS2012R2/lisa/setupscripts/Kdump.ps1
WS2012R2/lisa/xml/Kdump_Tests.xml

change to have LISA push the kdump dependency scripts to the test VM, rather than script side handling the copy process.

kdump dependency files change push to VM

---

WS2012R2/lisa/stateEngine.ps1

This is from https://github.com/LIS/lis-test/issues/580
DiagnoseHungSystem state will now reboot the VM and continue the testing
instead of stopping all the remaining tests.

Changed DiagnoseHungSystem behavior in stateEngine.ps1

---

WS2012R2/lisa/stateEngine.ps1
WS2012R2/lisa/utilFunctions.ps1

Added a function that will capture a console screenshot if VM enters
DiagnoseHungSystem state

DiagnoseHungSystem improvements

---

WS2012R2/lisa/setupscripts/Production_checkpoint.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_3Chain_VHD.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_ISO_NoNetwork.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_failback.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_iSCSI.ps1
WS2012R2/lisa/setupscripts/Production_checkpoint_partition.ps1

Due to missing ComputerName parameter, the Production Checkpoint scripts
failed on remote lisa runs.

Production Checkpoint improvements

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
WS2012R2/lisa/remote-scripts/ica/Kdump_Execute.sh
WS2012R2/lisa/remote-scripts/ica/Kdump_Results.sh
WS2012R2/lisa/remote-scripts/ica/Kdump_nfs_config.sh
WS2012R2/lisa/setupscripts/Kdump.ps1

Kdump_nfs TC improvements

---

WS2012R2/lisa/stateEngine.ps1
WS2012R2/lisa/utilFunctions.ps1

Migrate change from xiaofeng, add property with "TC_COVERED"

Update stateEngine to support xunit xml result with TC_Covered

---

WS2012R2/lisa/setupscripts/NET_Corruption.ps1

Added ComputerName parameter to allow test running on different host.

Fixed TCP_Corruption running on different host

---

WS2012R2/lisa/setupscripts/NET_filecopy_scp.ps1

Added server name to file path in order to fix the problem of running the test on remote servers.

Fixed FileCopySCP TC when being run remotely

---

WS2012R2/lisa/remote-scripts/ica/NET_LEGACY.sh
WS2012R2/lisa/setupscripts/NET_ADD_NIC_MAC.ps1
WS2012R2/lisa/setupscripts/NET_Add_Max_NIC.ps1
WS2012R2/lisa/setupscripts/NET_MAX_NIC.ps1
WS2012R2/lisa/setupscripts/NET_REMOVE_NIC_MAC.ps1

Related with three cases, MaxNIC, LegacySyntheticNetwork,MaxLegacyNIC, skip for Generation 2 VM.

update NET Legacy related case to skip in Generation 2 VM

---

WS2012R2/lisa/setupscripts/NET_Hang_Vxlan.ps1

replace private key hard code to parameter

Update net hang vxlan private key

---

WS2012R2/lisa/setupscripts/DM_CONFIGURE_MEMORY.ps1
WS2012R2/lisa/setupscripts/STRESS_BootLargeMemory.ps1
WS2012R2/lisa/xml/StressTests.xml

Added a test case to boot the VM with more than 67GB of RAM and check
how much is accessible by VM.

Added new TC to StressTests suite

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

Added output messages for TimeSync_NTP test case.

Add output messages for TimeSync_NTP TC

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Fixed path formatting to allow working with remote VMs on Nano server.

Fixed CreateVMs.ps1 to work with Nano server

---

WS2012R2/lisa/setupscripts/SR-IOV_GetMLNXInfo.ps1
WS2012R2/lisa/xml/SR-IOV.xml

Added a script to collect information about the Mellanox driver
from the host.

Added Mellanox driver details logging

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Fixed path formating in case of missing ending backslash.

Fixed path generation

---

WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1

Updated TC exit statuses

---

WS2012R2/lisa/setupscripts/SR-IOV_GetMLNXInfo.ps1

Fixed the path generation process in case of network path usage.

Fixed path generation for host driver info

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh
WS2012R2/lisa/remote-scripts/ica/Core_Config_TimeSync.sh
WS2012R2/lisa/setupscripts/INST_timesync_change_state.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1

Updated time sync configuration script to address issue #764

Updated TimeSync configuration script

---

WS2012R2/lisa/setupscripts/STOR_VHDXResize_Basic.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_BasicLM.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_DiskOver2TB.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowFS.ps1
WS2012R2/lisa/setupscripts/STOR_VHDXResize_GrowShrink.ps1

Added error messages in console summary for easier debugging

Added error messages to console output

---

WS2012R2/lisa/stateEngine.ps1

Fixed an issue where screenshot of the VM console failed if the log
directory was on a network share.

Console screenshot fix

---

WS2012R2/lisa/remote-scripts/ica/Perf_BuildKernel.sh
WS2012R2/lisa/remote-scripts/ica/collect_gcov_data.sh
WS2012R2/lisa/setupscripts/GCOV_Data_Group.ps1
WS2012R2/lisa/setupscripts/GcovDataCollect.ps1
WS2012R2/lisa/setupscripts/TCUtils.ps1
WS2012R2/lisa/tools/gcov/README.md
WS2012R2/lisa/tools/gcov/gcov_group
WS2012R2/lisa/tools/gcov/gcovr-group.py
WS2012R2/lisa/utilFunctions.ps1
WS2012R2/lisa/xml/GcovKvpTests.xml

Adding the scripts that :
-build the kernel with the module required by gcov.  
-collect the coverage data from VM.
-process the data into human readable html form. 
I added more details in the README file.

Adding code coverage collecting and processing feature

---

WS2012R2/lisa/remote-scripts/ica/Performance_FIO.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
WS2012R2/lisa/tools/middleware_bench/db_utils.py
WS2012R2/lisa/tools/middleware_bench/tests/run_terasort.sh

- Allow ntttcp test to collect logs even in case of failure
- Update terasort version
- Disable db table creation

Update perf tests

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
WS2012R2/lisa/remote-scripts/ica/Kdump_Execute.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh

Fixed Kdump TC for generation 2 VMs with older kernels

Fixed Kdump for gen2 VMs with older kernels

---

WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/file_parser.py
WS2012R2/lisa/Infrastructure/lisa-parser/lisa_parser/test_run.py
WS2012R2/lisa/remote-scripts/ica/perf_iperf_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_iperf_server.sh
WS2012R2/lisa/tools/middleware_bench/results_parser.py

Fix middleware_bench udp parser
Update iperf test parallel run method and adjust parser

Perf update iperf test 

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh

Changed the way crashkernel param is added. The config is now made in the boot file directly. Duplicate code was also removed

Kdump_config.sh improvements

---

WS2012R2/lisa/utilFunctions.ps1

In case the VM becomes unresponsive the automation is now able to
exit on time out.

Bypass automation freeze in case of system hang

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Fixed an issue where an error shows up when trying to create a clustered
VM. This happens because a VM already exists on the cluster but it's
located on the secondary node.

CreateVMs.ps1: Added cleanup for second cluster node

---

WS2012R2/lisa/setupscripts/KVP_Basic.ps1
WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1
WS2012R2/lisa/xml/KvpTests.xml

Added a test to check if disable and reenable of KVP service
results in failure of KVP daemon on the VM.

Added new TC for KVP tests

---

WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1

Added quotes to reduce risk of error occurence

Improved code syntax

---

WS2012R2/lisa/Infrastructure/patch-utils/config.py
WS2012R2/lisa/Infrastructure/patch-utils/edit_xml.ps1
WS2012R2/lisa/Infrastructure/patch-utils/git.py
WS2012R2/lisa/Infrastructure/patch-utils/patch_boot_test.ps1
WS2012R2/lisa/Infrastructure/patch-utils/patch_manager.py
WS2012R2/lisa/Infrastructure/patch-utils/patch_utils.py
WS2012R2/lisa/Infrastructure/patch-utils/server.py
WS2012R2/lisa/Infrastructure/patch-utils/utils.py
WS2012R2/lisa/remote-scripts/ica/install_lis_next.sh

A new feature was created in order to integrate upstream changes in lis-next codebase.
The cli tool that is being added provides multiple commands for creating new patches from
upstream linux commits and for testing those patches on existing lis-next code.

Add feature for patch integration

---

WS2012R2/lisa/remote-scripts/ica/perf_iperf_client.sh
WS2012R2/lisa/remote-scripts/ica/perf_iperf_server.sh
WS2012R2/lisa/remote-scripts/ica/perf_ntttcp_client.sh
WS2012R2/lisa/tools/middleware_bench/AWS.py
WS2012R2/lisa/tools/middleware_bench/Azure.py
WS2012R2/lisa/tools/middleware_bench/cmdshell.py
WS2012R2/lisa/tools/middleware_bench/connector.py
WS2012R2/lisa/tools/middleware_bench/constants.py
WS2012R2/lisa/tools/middleware_bench/db_utils.py
WS2012R2/lisa/tools/middleware_bench/requirements
WS2012R2/lisa/tools/middleware_bench/results_parser.py
WS2012R2/lisa/tools/middleware_bench/tests/run_network.sh
WS2012R2/lisa/tools/middleware_bench/tests/run_sqlserver.sh
WS2012R2/lisa/tools/middleware_bench/utils.py

Update prerequisites and parameters for iperf and ntttcp
Azure Windows VM creation support 
Add SQLServer benchcraft test and parser
Add testrun timeout

Update perf tests and add Azure Windows VM support

---

WS2012R2/lisa/setupscripts/CreateVMs.ps1

Recent commit on CreateVMs.ps1 was failing in certain configurations.
This is fixing those situations.

CreateVMs.ps1 fix

---

WS2012R2/lisa/setupscripts/collect_gcov.ps1

Currently the directory name for code coverage report is date, but it is not clearly for user, so replace the date to kernel version

Enhance: Update the directory name for code coverage report to add kernel version

---

WS2012R2/lisa/setupscripts/KVP_Max_Read.ps1
WS2012R2/lisa/xml/KvpTests.xml

A new test was added in order to
check if the KVP daemon works properly
when reading a large number of entries.
The test creates a new kvp pool file,
using the kvp client and performs a kvp
read from the host, checking the status
of the kvp daemon on the guest VM.

Add KvpMaxRead Test

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh

Updated LTP to latest version to fix compiling errors and fixed
indentation

Updated LTP version

---

WS2012R2/lisa/stateEngine.ps1

remove 3 lines, set currentTest="done" and updateState as finisheded.
Currently issue is that if postTestScript failed, it will exit the whole Lisa test.
Thank you

Update stateEngine runPostTestScript to avoid exit test when fail

---

WS2012R2/lisa/remote-scripts/ica/utils.sh

Added os_PACKAGE variable for SLES to utils.sh

utils.sh improvement

---

WS2012R2/lisa/remote-scripts/ica/shielded_verify_dependencies.sh
WS2012R2/lisa/remote-scripts/ica/shielded_verify_lsvm.sh
WS2012R2/lisa/remote-scripts/ica/shielded_verify_lsvmprep.sh
WS2012R2/lisa/remote-scripts/ica/shielded_verify_passphrase_noSpace.sh
WS2012R2/lisa/setupscripts/Shielded_Add_DecryptVHD.ps1
WS2012R2/lisa/setupscripts/Shielded_Remove_DecryptVHD.ps1
WS2012R2/lisa/setupscripts/Shielded_install_lsvm.ps1
WS2012R2/lisa/setupscripts/Shielded_not_encrypted_vhd.ps1
WS2012R2/lisa/xml/Shielded_PreTDC.xml

This is pre-templatization automation (LSVM-PRE). Tests included:
-- LSVM-PRE-01: Verify the distro specific Linux Shielded VM tools
package is installed.
-- LSVM-PRE-02: Verify dependent packages are installed.
-- LSVM-PRE-03: Verify lsvmprep correctly configures the Linux VHDX for
templatization
-- LSVM-PRE-04: Run lsvmprep on VHDX where root partition is not
encrypted.
-- LSVM-PRE-05: Root partition passphrase is not the well-known
passphrase
-- LSVM-PRE-06: Insufficient space to encrypt boot partition
Beside the above test cases, a few more scripts were needed:
--Setupscript to attach the passthrough disk that can decrypt the
encrypted VHD -  Shielded_Add_DecryptVHD.ps1
-- Cleanup script to remove the passthrough disk
-Shielded_Remove_DecryptVHD.ps1
-- Install script for lsvmtools. …

Added Linux Shielded VMs automation testing - Pre-TDC

---

WS2012R2/lisa/lisa.ps1
WS2012R2/lisa/setupscripts/CreateVMs.ps1

A new feature was added in order to save the output
of the tested VMs in separate log files.
Output log files are created for each VM used and
saved in the test suite log path, under the following
name format "${vmName}-icaserial.log"
Also the CreateVMs setup script was update in order
to configure the com2 port with an unique path.

 Save VM output to log file

---

WS2012R2/lisa/remote-scripts/ica/Hyperv_Daemons_Files_Status.sh

Add condition to check hyperv-daemons in /lib/systemd/system-preset/90-default.preset
- For rhel7.3+, no need to check;
- Others, need to check

Add condition for checking hyperv daemons in 90-default.preset

---

WS2012R2/lisa/remote-scripts/ica/modules_check.sh
WS2012R2/lisa/xml/CoreTests.xml

Add modules check for gen1, except hyperv_keyboard

Add gen1 modules check, exclude hyperv_keyboard

---

WS2012R2/lisa/Infrastructure/aio.sh

Added some packages needed for testing.

Added packages for SLES distro

---

WS2012R2/lisa/remote-scripts/ica/linux_azure_install.sh

Added the test script that install linux-azure kernel on Ubuntu

Linux Azure kernel install script

---

WS2012R2/lisa/setupscripts/Deploy_scenarios.ps1
WS2012R2/lisa/setupscripts/NET_ADD_NIC_MAC.ps1
WS2012R2/lisa/xml/LIS_Scenarios.xml

Two new tests were added in order to check the behavior of the unbonding script on lis next install/upgrades

Add new deploy scenarios tests

---

WS2012R2/lisa/remote-scripts/ica/NET_MAX_NIC.sh

Updated MaxNICs test cases for better failure handling.

Improved MaxNICs TC

---

WS2012R2/lisa/setupscripts/FCOPY_disableEnable.ps1
WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1

Improved the way in which the daemon name is being handled by the
test script for better accuracy.

Improved daemon name handling

---

WS2012R2/lisa/remote-scripts/ica/CORE_TimeSync_NTP.sh

In some cases the NTP daemon would only listen to IPv6. By using the
loopback IP as parameter it is forced to listen on IPv4.

Updated TimeSync_NTP TC to use IPv4

---

WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1

For RedHat distributions older than 7.3, LIS 4.x drivers are needed.
If LIS 4.x drivers are not present skip the test.

Skip test KVP_TestRescind if RHEL distro is older than 7.3

---

WS2012R2/lisa/utilFunctions.ps1

Replaced init 0 command with Stop-VM.

Replace init 0 with Stop-VM

---

WS2012R2/lisa/remote-scripts/ica/install_kernel.sh

-replace rpm -i with yum install, to install dependency packages
-remove hyperv daemons before install to fix daemon install conflicts

Fix rpm kernel install

---

WS2012R2/lisa/setupscripts/AddVhdxHardDisk.ps1
WS2012R2/lisa/setupscripts/RemoveVhdxHardDisk.ps1

If a variable contains a string with special characters, the match
pattern will better split the variable from the cotents of it.

Better handle of param split and validation

---

WS2012R2/lisa/setupscripts/NET_filecopy_scp.ps1

Better handle pscp path if it contains blank spaces.
Also bumped file-system format to ext4.
Verify job status and display job failure.
Other minor text corrections and output messages.

[net copy scp] Fix path handling and other fixes

---

WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1

Fixed paths for test VHD and child VHD, including a predefined name for
the child VHD.
remove unused variable newVm

Hearbeat_PauseCritical code fixes

---

WS2012R2/lisa/remote-scripts/ica/modules_check.sh

In case there are built-in modules, exclude them from testing.

Remove built-in modules from test

---

WS2012R2/lisa/remote-scripts/ica/lsvmbus_basic.sh
WS2012R2/lisa/remote-scripts/ica/lsvmbus_target.sh

try to Install hyperv-tools before test lsvmbus

lsvmbus: Add yum install hyperv-tools for rhel and centos

---

WS2012R2/lisa/Infrastructure/json-parser/README.md
WS2012R2/lisa/Infrastructure/json-parser/parser.py
WS2012R2/lisa/Infrastructure/json-parser/requirements.txt
WS2012R2/lisa/Infrastructure/json-parser/tests.json
WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.Tests.ps1

Added JSON parsed that will be used to insert Shielded VMs testing
results into the database. Also made a small change to Shielded PRE-TDC
script

Shielded VMs: Added JSON parser

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_UpgradeKernel.sh
WS2012R2/lisa/setupscripts/Shielded_DEP.ps1
WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.Tests.ps1
WS2012R2/lisa/setupscripts/Shielded_TDC.Tests.ps1
WS2012R2/lisa/setupscripts/Shielded_TDC.ps1

Various fixes that improves overall Shielded VMs false positive test
results

Shielded VMs: Small fixes

---

WS2012R2/lisa/setupscripts/KVP_TestRescind.ps1

Check for major kernel version in case of upstream kernels before
skipping test case.

Enhanced kernel version detection

---

WS2012R2/lisa/Infrastructure/aio.sh

The minimal flavor for SLES does not have autoconf and make binaries
installed by default, therefore they must be installed before using them.
Moved the package install section before any other application install.

Update aio for SLES

---

WS2012R2/lisa/remote-scripts/ica/NET_Configure_Vxlan.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh

Added support for SLES 15 distro detection and small changes to
NET_VxLAN testing for better error handling.

Improvements for SLES distro detection

---

WS2012R2/lisa/OSAbstractions.ps1
WS2012R2/lisa/stateEngine.ps1

This is fixing an error regarding GetOSType function. In some cases it
returned a null value and lisa failed.

GetOSType fix

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
WS2012R2/lisa/setupscripts/SR-IOV_enable.ps1

- update iperf3 install method to rely on github
- small code fixes and code indentation

SR-IOV code stabilization

---

WS2012R2/lisa/remote-scripts/ica/lis_install.sh
WS2012R2/lisa/xml/lis_pipeline_bvt.xml

This script will download LIS and install it. A new XML that will use
this script was also created

Added LIS install script and xml

---

WS2012R2/lisa/remote-scripts/ica/lis_install.sh

1. Fixed identation
2. Fixed unavailable function issue
3. Added Warning skip if kernel versions don't match

lis_install.sh - Identation and code fixes

---

WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1
WS2012R2/lisa/xml/CoreTests.xml

Modified Core_Heartbeat_PausedCritical.ps1 so that the drive letter is picked randomly from the available drive letters.
Modified CoreTests.xml because it is not necessary anymore to have the drive letter into the parameters.

Core_Heartbeat_PausedCritical - Modified drive letter input

---

WS2012R2/lisa/remote-scripts/ica/lis_deploy_scenarios_install.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh
WS2012R2/lisa/setupscripts/deploy_scenarios_pipeline.ps1

Added various code fixes and additional checks.

Deploy scenarios improvements

---

WS2012R2/lisa/remote-scripts/ica/NET_Multicast.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_Multicast.sh

In newer kernels/drivers, allmulti is not enabled by default and this
causes the Multicast TC to fail. TCs will now enable allmulti before
testing multicast

Multicast TC: Added ethtool allmulti option

---

WS2012R2/lisa/setupscripts/CORE_reload_modules.ps1

Updated the TC script to refresh the IP address of the VM before
checking for the state.txt file content.

Updated StressReloadModules TC

---

WS2012R2/lisa/remote-scripts/ica/shielded_deployed_functions.sh
WS2012R2/lisa/setupscripts/Shielded_DEP.ps1
WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.Tests.ps1
WS2012R2/lisa/setupscripts/Shielded_PRE-TDC.ps1
WS2012R2/lisa/setupscripts/Shielded_PRO.Tests.ps1
WS2012R2/lisa/setupscripts/Shielded_PRO.ps1

- CompatibilityForMigrationEnabled option set on True was causing
issues with luks for RHEL/SLES. Changing it to False to solve this.
- Changed the recovery password (the old one was too weak)
- Added additional checks on provisioning TCs
- Small overall fixes

Shielded VMs: Various fixes

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_Utils.sh
WS2012R2/lisa/remote-scripts/ica/perf_utils.sh
WS2012R2/lisa/setupscripts/SR-IOV_Deattach_NIC.ps1
WS2012R2/lisa/setupscripts/SR-IOV_DisableNIC.ps1

mlx4_core can be built in the kernel, and only mlx4_en will show in lsmod

SR-IOV check for mlx4_core or mlx4_en

---

WS2012R2/lisa/xml/CoreTests.xml
WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
WS2012R2/lisa/xml/lis_pipeline_bvt.xml
WS2012R2/lisa/xml/lis_pipeline_fvt.xml

higher CPU count might require additional RAM on the VM

Multi_Cpu_Test - use custom RAM

---

WS2012R2/lisa/setupscripts/deploy_scenarios_pipeline.ps1

Improved syntax and small code fixes

deploy_scenarios_pipeline.ps1 minor fixes

---

WS2012R2/lisa/setupscripts/SR-IOV_Stress_SavePause.ps1

The old sleep times weren't enough for the VF to be able to disconnect
and connect again. This caused the automation to fail

SR-IOV: Changed sleep times in Stress Save/Pause TCs

---

WS2012R2/lisa/remote-scripts/ica/lis_install.sh
WS2012R2/lisa/setupscripts/Runtime_Mem_Configure.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd_Chunks.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_HotAdd_reboot.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_MultipleAddRemove.ps1
WS2012R2/lisa/setupscripts/Runtime_Mem_StressHotRemove.ps1

1. Added Skipped state to Runtime Memory Resize tests for hosts with WS version lower than 2016
2. Disabling SELinux in lis_install.sh

TC improvements

---

WS2012R2/lisa/setupscripts/Core_Heartbeat_PausedCritical.ps1

Because of the different VHDX filesizes the values supplied to dd
have to vary based on the free space left on the ChildVM partition.
Also, for Ubuntu based VHDXs the amount of reserved root space has
to be reduced.

Updated Heartbeat_PausedCritical parameters

---

WS2012R2/lisa/tools/middleware_bench/tests/run_postgresql.sh

1 Hung issue which missing -y when run yum install
2 Postgresql configuration files change

Fix middleware.test_postgresql against Amazon Linux

---

WS2012R2/lisa/Infrastructure/aio.sh
WS2012R2/lisa/remote-scripts/ica/Sysbench.sh

When compiling the Sysbench tool the xxd package is required. This
package comes with the vim package.

Add vim package for SLES

---

WS2012R2/lisa/setupscripts/FC_AddFibreChannelHba.ps1
WS2012R2/lisa/setupscripts/FC_SaveRestoreVM.ps1

If not set Set-VMSecurity -VirtualizationBasedSecurityOptOut $true, will pop up error when adding FC adapter to 2016 Gen2 vm.
Thank you.

Update FC_AddFibreChannelHba to set-security for gen2 vm on 2016

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh
WS2012R2/lisa/remote-scripts/ica/Kdump_Execute.sh
WS2012R2/lisa/remote-scripts/ica/NUMA_off_kernel.sh
WS2012R2/lisa/remote-scripts/ica/ping_client.sh
WS2012R2/lisa/remote-scripts/ica/ping_server.sh
WS2012R2/lisa/remote-scripts/ica/utils.sh

Add redhat_8 distro for partial test cases: e.g. network test cases and kdump_config and kdump_execute, numa_off_kernel, ping_client and ping_server.
Thank you.

Minor update utils.sh and kdump.sh to support rhel 8 for distro

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh
WS2012R2/lisa/xml/LTP.xml

XML indentation fixed. Removed faulty git parameter.

LTP testcase updates

---

WS2012R2/lisa/xml/test_kernel_pipeline.xml

change was made in commit 3d36993c260d0890e1cb294874f65b4d22e74688

Reverted to install_kernel

---

WS2012R2/lisa/remote-scripts/ica/check_clockevent.sh
WS2012R2/lisa/xml/CoreTests.xml

Add clockevent check case

---

WS2012R2/lisa/setupscripts/deploy_scenarios_pipeline.ps1
WS2012R2/lisa/tools/bondvf.sh
WS2012R2/lisa/xml/lis_pipeline_deploy_scenarios.xml

Because bondvf.sh was missing in some cases, we are adding bondvf.sh
upload from lisa.  This is improving LISDeploy-09 and LISDeploy-10
stability

Deploy Scenarios: Added bondvf.sh

---

WS2012R2/lisa/remote-scripts/ica/CORE_LISmodules_version.sh

Script didn't run properly on Ubuntu. Added rpm check to fix this.

CORE_LISmodules_version.sh fix

---

WS2012R2/lisa/remote-scripts/ica/CORE_StressReloadModules.sh
WS2012R2/lisa/remote-scripts/ica/NET_Corruption.sh
WS2012R2/lisa/remote-scripts/ica/NET_VerifyBootNoNIC.sh
WS2012R2/lisa/remote-scripts/ica/NET_VerifyHotAddMultiNIC.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_ModuleReload.sh
WS2012R2/lisa/remote-scripts/ica/SR-IOV_VerifyVF_basic.sh
WS2012R2/lisa/remote-scripts/ica/STOR_VSS_StopNetwork.sh
WS2012R2/lisa/setupscripts/SR-IOV_ChangeRSS.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MeasureDisableVF.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MoveVHD.ps1
WS2012R2/lisa/setupscripts/SR-IOV_UpgradeKernel.ps1

net-tools are deprecated, replace ifconfig and related with ip commands.
Some code cleanup and optimizations.

network tests: replace ifconfig with ip commands

---

WS2012R2/lisa/xml/hyperv_bvt.xml
WS2012R2/lisa/xml/hyperv_fvt.xml
WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
WS2012R2/lisa/xml/lis_pipeline_bvt.xml
WS2012R2/lisa/xml/lis_pipeline_fvt.xml
WS2012R2/lisa/xml/ubuntu_azure_kernel_fvt.xml

Remove old test case and add all 4 new TCs from main Core tests xml

add clocksource TCs

---

WS2012R2/lisa/Infrastructure/Replace-FileString.ps1

Used to replace strings within files

Added Replace-FileString.ps1

---

WS2012R2/lisa/remote-scripts/ica/Core_Time_Clockevent.sh
WS2012R2/lisa/remote-scripts/ica/Core_Time_Clocksource.sh

code functionality is the same as for ubuntu.

time TCs: add support for debian

---

WS2012R2/lisa/remote-scripts/ica/check_traces.sh
WS2012R2/lisa/remote-scripts/ica/verify_ifdown_ifup.sh
WS2012R2/lisa/xml/NET_Tests.xml
WS2012R2/lisa/xml/hyperv_fvt.xml
WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
WS2012R2/lisa/xml/lis_pipeline_fvt.xml
WS2012R2/lisa/xml/ubuntu_azure_kernel_fvt.xml

Added check for call traces during the test execution.
Code cleanup in ifdown/ifup script.
Added test case in FVT xml files.
Small test case rename - first lower leter.
Fix indentation and blank spaces in check_traces.sh

ifdown-ifup TC improvements

---

WS2012R2/lisa/remote-scripts/ica/UIO_Basic.sh
WS2012R2/lisa/xml/hyperv_bvt.xml
WS2012R2/lisa/xml/hyperv_fvt.xml
WS2012R2/lisa/xml/kernel_pipeline_bvt.xml
WS2012R2/lisa/xml/kernel_pipeline_fvt.xml
WS2012R2/lisa/xml/lis_pipeline_bvt.xml
WS2012R2/lisa/xml/lis_pipeline_fvt.xml
WS2012R2/lisa/xml/ubuntu_azure_kernel_fvt.xml

Add uio TC to all validation.
Minor updates to UIO_Basic.sh:
- reports driver version
- checks if module is defined in the kernel configuration

Add uio TC to all BVT/FVT

---

WS2012R2/lisa/setupscripts/NET_UTILS.ps1
WS2012R2/lisa/setupscripts/SR-IOV_MoveVHD.ps1
WS2012R2/lisa/xml/SR-IOV.xml
WS2012R2/lisa/xml/kernel_pipeline_sriov.xml

Use switch name as a param for all tests and update related placeholders.
Code formatting fixes

SR-IOV param update

---

WS2012R2/lisa/remote-scripts/ica/LTP_test.sh

Updated LTP_test.sh : LTP version

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh

Minor update kdump_config for hyper-v 2012 host.
Thank you.

Update Kdump_Config for hyper-v 2012 host

---

WS2012R2/lisa/setupscripts/NET_BootNoNICHotAddNIC.ps1

Added longer time out and showing of output on fail

Updated NET_BootNoNICHotAddNIC.ps1

---

WS2012R2/lisa/remote-scripts/ica/SR-IOV_DisableVF.sh
WS2012R2/lisa/setupscripts/SR-IOV_ChangeRSS.ps1

Code has been updated to avoid false positives.
Test DisableVF                 : Passed
Test covers SRIOV-4
VF is present on VM!
VF count: 1
Successfully pinged 10.11.12.32 with VF down
Successfully disabled and enabled VF
Test Change_RSS                : Passed
This script covers test case: SRIOV-16
The throughput before changing the RSS profile is 28.8 Gbits/sec
The throughput after changing RSS profile is 29.6 Gbits/sec

SR-IOV: code improvements

---

WS2012R2/lisa/setupscripts/SR-IOV_Ping_DisableVF.ps1

Before SR-IOV_Ping_DisableVF compare one value of PingResults.log, which makes test case not stable, Sometimes test case failed, after rerun maybe pass. Comparing RTT average value(enable, disable, re-enable again) during 30 seconds is more reliable than one instant value.
Thank you.

Refine SR-IOV_Ping_DisableVF one value compare to average value

---

WS2012R2/lisa/setupscripts/eventid_18602_regression.ps1

Hi Chris,
Looks that before original MultipleReboot.ps1 has been removed and replaced as eventid_18602_regression,  running list in the fvt.xml files use MultipleReboot.ps1.  So change back and refine some log output.

Rename eventid_18602_regression to MultipleReboot.ps1

---

WS2012R2/lisa/remote-scripts/ica/Kdump_Config.sh

Hi Chris,
Refer to bug https://bugzilla.redhat.com/show_bug.cgi?id=1637875, GRUB_CMDLINE_LINUX does not work probably for some reason. From the comment of developer, if kernelopts and other grub.cfg variables are defined in /boot/efi/EFI/redhat/grubenv for EFI systems and /boot/grub2/grubenv for legacy BIOS. This file should not be edited with a text editor. It can be modified using:
grub2-editenv - set kernelopts=”rd.debug=1 rhgb”.
Based on above reason, do minor change for Kdump_Config.sh
Thank you.

Update kdump for grub2-editenv to set kernelopts

---

WS2012R2/lisa/remote-scripts/ica/verify_ifdown_ifup.sh

Do minor update:
1) Setting NetInterface="eth1" and Ping -I eth1. 
2) Change the loop number, from 4 to 10, even 10 is still lower loop number.
3) Change sleep 15 to sleep 5.
Thank you.

Minor update verify_ifdown_ifup.sh to use eth1
